gopherjs/gopherjs

- compiler/compiler.go
- compiler/prelude/prelude.go
I want to use gopherjs for [JavaFX](http://docs.oracle.com/javase/8/javase-clienttechnologies.htm) with [Nashorn](http://www.oracle.com/technetwork/articles/java/jf14-nashorn-2126515.html) such as a following code.
[My article](http://qiita.com/tenntenn/items/e61822b265bc2b8f6c88)  explains this code.
(Sorry! This article is written in Japanese.)
* https://gist.github.com/tenntenn/f8c89022f7139a3c15bf
In Nashorn, we can get the global object from only `this` in top level.
But gopherjs cannot get top level `this`.
So I fix it.
Please review and merge my pull request.
> use top level this as global object

- tool.go
`http.Dir` expects a native filepath, so it's correct to use `filepath.Join` instead of hardcoding the filepath separator as '/'.
See https://godoc.org/net/http#Dir for details:
> While the FileSystem.Open method takes '/'-separated paths, a Dir's string value is a filename on the native file system, not a URL, so it is separated by filepath.Separator, which isn't necessarily '/'.
> Use filepath.Join to manipulate a filepath.

- compiler/prelude/goroutines.go
- tests/misc_test.go
I imagine this problem shows up elsewhere, but the clearest
demonstration I can find is in the behavior of runtime.NumGoroutine():
The second time a goroutine blocks, and every time thereafter, it
invokes the goroutine exiting logic. This causes runtime.NumGoroutine to
underreport the number of goroutines, because the exiting logic includes
decrementing that count. In my testing, runtime.NumGoroutine was often
negative.
The fix is pretty simple. When calling the `r.$blk` closure, return its
output, which may itself be another closure.
> fix for goroutine blocking bookkeeping

- compiler/natives/net/http/http.go
There is a bug on Firefox that causes all requests sent via the net/http package (using the underlying XMLHttpRequest) to fail with the error message: `InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable`. The bug is caused when you try to access the responseType attribute of an XMLHttpRequest before it is open. Since I don't know when Firefox is going to fix this bug, I am proposing this simple workaround. All I did was move the line that set the responseType to be after the call to open.
The bug is described here: https://bugzilla.mozilla.org/show_bug.cgi?id=1110761. I have tested on OS X 10.10.2 and the latest version of Firefox. My fork also still works on the latest versions of Chrome and Safari.
See https://github.com/albrow/firefox-http-fail …
> Introduce a workaround for a XMLHttpRequest bug in Firefox.

- compiler/natives/runtime/runtime.go
The implementation returns 0, and leaves `pc` unchanged.
> Implement runtime.Callers

- tool.go
Print potential errors to stderr rather than stdout.
Use `syscall.Stderr` instead of hardcoding a magic number. It increases readability.
> gopherjs: Minor improvements.

- compiler/expressions.go
- compiler/package.go
- compiler/statements.go
Signature for `types.NewSignature` has changed in golang/tools@44761a8f84d6444f74938c73:
```diff
-func NewSignature(scope *Scope, recv *Var, params, results *Tuple, variadic bool) *Signature {
+func NewSignature(recv *Var, params, results *Tuple, variadic bool) *Signature {
```
See commits https://github.com/golang/tools/commit/f389b292089a2cf43f61f6ff6717250d14437be4 and https://github.com/golang/tools/commit/e5c3ebe4c75c7f8d84a92853cff976756a24faf9 for similar changes.
> Fix build (provide correct args to types.NewSignature).

- tool.go
Currently, only build and install commands make use of the tags flag to set custom build tags. Add this functionality to serve command, so it's possible to use custom build tags with serve.
Note that the tags flag was already added to the serve command, it was just unused:
```Go
cmdServe.Flags().AddFlag(flagTags)
```
> Add --tags flag support to serve command.

- tool.go
Previously, if there was already a {base}.js file on disk (possibly as a result of running `gopherjs build` in the past), it would take higher precedence than the freshly compiled {base}.js file. Fix that by rearranging the serving precedence logic as follows:
1. {base}.js && valid Go command in folder -> compiled {base}.js
2. {base}.js.map && valid Go command in folder -> compiled {base}.js.map
3. Look in all Go workspaces (GOPATH and GOROOT)
4. index.html && valid Go command in folder -> our own stub index.html
This way, if there's an index.html file on disk, it takes higher precedence, but not {base}.js and {base}.js.map files.
Needed for https://github.com/gopherjs/gopherjs.github.io/pull/25.
> gopherjs serve: Fix precedence of served files.

- build/build.go
- tool.go
Fixes #260.
Add `IsTest` bool to `PackageData` to specify if package is being build normally or for tests.
`parse` was made unexported. It was undocumented, and not used by any external packages. Unless there's a good reason to export it, it's better not to, as that keeps the API smaller and simpler, allows internal code to change more easily. For this fix, I changed signature of `parse` to accept an extra parameter.
> Do not include _test.go files (of stdlib deps) when not building tests.

- compiler/expressions.go
This would've been more helpful to have when #256 was originally reported, before it was fixed in 427a88ec9ab6ff7fcb5a27f5ec752e193e809e04 (and a few subsequent commits). But I've already written it on my branch where I looked into what it'd take to fix #256, so might as well contribute it.
It makes the code more consistent (all other panics have a meaningful message associated), and it might come in handy in 10 years when a new [selection kind](https://godoc.org/golang.org/x/tools/go/types#SelectionKind) is added.
Another note. My original code used `panic(fmt.Errorf(...))` style, but I changed it to `panic(fmt.Sprintf(...))` style for consistency with existing code. But I still think using `panic(fmt.Errorf(...))` is slightly nicer.
> Have more helpful unexpected panic messages.

- tool.go
When specified port was 0, that means for listen to "pick any available port", the output did not state which port was chosen. By printing the listener's `Addr()`, we print the actual address (host and port) being served.
Also improve handling of printing correct "serving at ..." messages when dealing with IPv6.
Resolves #265.
Closes #264 because it includes all of its commits, so if this PR is merged, that one becomes redundant. Alternatively, that one can be merged first, and this one can be rebased on top. I just made it in advance.
> gopherjs serve: Allow specifying host and port via http flag, handle port 0.

- compiler/natives/time/time.go
- compiler/prelude/jsmapping.go
This is an implementation of possible solution 2, with modifications based on additional findings.
The reason I went with 2 instead of 1 as originally planned is described in https://github.com/gopherjs/gopherjs/issues/279#issuecomment-136095365.
See commit messages for full details.
This should make all tests pass.
> Implement possible solution 2 fix for #285.

- compiler/expressions.go
- tests/run.go
Fixes #297.
Handle `types.UntypedInt` value of `types.BasicKind` in `fixNumber`. Treat it like `types.Int` and `types.Int32`.
Update error message to be more readable.
> Fix fixedbugs/bug180.go and fixedbugs/issue12133.go compiler panics.

- compiler/prelude/numeric.go
`$divComplex` for now uses implicit `Infinity` and `NaN` values (with divisions by zero and zero divided by zero). This improves the code readability by making these expressions explicit.
> Explicit values in $divComplex

- build/build.go
This simply copies the same functionality from ImportPackage(). Perhaps it
should be factored into a common function.
This appears to solve bug #306, but causes some test failures, which I will investigate later.
> Include *.inc.js files in `gopherjs build` mode.

- build/build.go
- tool.go
This PR attempts to follow @neelance's suggestion in #328 & #330, with some minor refactoring of build/build.go.
With this PR, `jsFilesFromDir()` is now called from `Import()`, the new `ImportDir()`, and `BuildDir()` (which seems to be a bit of an exception to the idea of using `Import*` to gather all the data used to build a package (not to mention the other exception of `ImportPackage()`).  I'm beginning to understand what Richard was referring to in his comment on #330.  And as such, in the grand scheme of things, this PR may make things worse rather than better... But it does seem to at least solve this immediate issue, so if a more proper fix is a long time off, I hope this might be considered for merge.
> Another try at handling *.inc.js cleanly

- build/build.go
- compiler/compiler.go
fix #351 
by adding field `compiler.Archive.JSDecls` to seperate included js code from the genereate js code and  then write the included js code just before gopherjs package declarations to avoid variable name shadowing.
> include *.inc.js in seperate scope to avoid package variable shadowing 

- build/build.go
- tests/run.go
- tool.go
And use the -q flag when running official Go tests, to avoid test failures for "invalid output" when gopherjs emits warnings about not loading the source-map-support module:
FAIL    fixedbugs/issue9006.go  0.326s
incorrect output
gopherjs: Source maps disabled. Use Node.js 4.x with source-map-support module for nice stack traces.
> Add --quiet commandline option to suppress non-fatal warnings in output

- tests/run.go
For some reason, I'm unable to get nodejs to find the source-map-support module when running the test suite, which causes every one of the official go tests to fail with "invalid output":
FAIL    fixedbugs/issue9006.go  0.326s
incorrect output
gopherjs: Source maps disabled. Use Node.js 4.x with source-map-support module for nice stack traces.
As running tests with source maps doesn't seem especially valuable to me, this patch attempts to remedy the problem by filtering out this text from the output of the tests
> Filter gopherjs warnings from test output.

- tool.go
Currently, if GOPATH isn't set, a rather unfriendly stack trace is generated. Something like:
```
panic: runtime error: index out of range
goroutine 1 [running]:
github.com/gopherjs/gopherjs/build.Import(0x61e420, 0x7, 0x0, 0x0, 0x0, 0x9067b0, 0x0, 0x0, 0xc8200cea90, 0x0, ...)
/Users/rodarmor/src/tumlt-app/src/github.com/gopherjs/gopherjs/build/build.go:97 +0xdd9
```
This adds a check to init() to print a friendlier error message. I reused the error message that the go tool prints out.
Thanks for GopherJS, it's f'in sweet :)
> Make error friendlier if GOPATH is not set

- compiler/statements.go
- tests/deferblock_test.go
This issue arises when re-winding the stack to complete a blocking function call inside a deferred function.  More specifically it occurs in functions that call blocking functions both with the defer keyword and in return statements.  A trivial example is given in [tests/deferblock_test.go](tests/deferblock_test.go), `ioutil.ReadFile` is an example of such a function from the stdlib.
All the test cases pass for me, and I've added a new file containing a test for this.  Let me know if there is any better way to test this.
> compiler: fix runtime exceptions with blocking deferred functions

- tool.go
This is an alternative to #334 to fix #303.  It uses the CWD for temp files, but falls back to using /tmp only for files found in the system GOROOT path, which should not be vulnerable to the security risks of running nodejs code in /tmp.
If there are ever other situations where we need to run tests in read-only directories, this will fail.  I don't know if such cases are likely ever to exist, but if they do, then #334 is probably the preferred solution.
> Use CWD for temp files, and fall back to /tmp only for upstream tests.

- compiler/analysis/bool.go
- compiler/analysis/escape.go
- compiler/analysis/info.go
- compiler/analysis/sideeffect.go
- compiler/astutil/astutil.go
- compiler/compiler.go
- compiler/expressions.go
- compiler/filter/incdecstmt.go
- compiler/package.go
- compiler/statements.go
- compiler/typesutil/typesutil.go
- compiler/utils.go
- third_party/importer/export.go
- third_party/importer/import.go
- third_party/importer/predefined.go
- tool.go
Do not merge, this PR is a work in progress. It's created for initial review and to avoid potential duplicate work.
With the release of Go 1.5, go/types and some related packages have moved from golang.org/x/tools subrepo to standard library. We can start using them. This PR is about making that so.
There are currently 3 commits, first one is clean and ready, the other two are WIP and need some work.
We need to use golang.org/x/tools/go/importer and x/tools/go/types/typeutil, which continue to live in golang.org/x/tools but have not yet been updated to import the new go/types. Instead, they still import the old golang.org/x/tools/go/types. Despite being identical, those packages have different import paths, and as a result the types they define cannot be used interchangeably.
For now, …
> Use go/types in Go 1.5 standard library.

- README.md
When writing Go code that is something more than just a very short snippet, it helps to organize code as a Go package. It may contain 1 or more .go files in a directory.
`go build` is primarily used with Go packages, as in `go build import/path`. We should suggest the same use of `gopherjs build`. That will make it easier for users to get started and grow their code, because they'll be able to split into multiple .go files without having to update their build step.
It's still possible to use `gopherjs build` with a list of files, just like `go build` can be used in the same way. But I don't think we should be recommending that as the primary usage mode. Users that still want this can discover it via `gopherjs help build`.
> README: Suggest working with Go packages by default.

- compiler/natives/runtime/runtime.go
The `runtime.MemStats` `GCCPUFraction` field  is expected by packages compiled for Go 1.5. This PR adds exactly that.
Please note that this PR does *not* update the field in any way. It will always be 0.0.
> Added GCCPUFraction to runtime.MemStats

- tool.go
Fixes #392.
/cc @neelance I have no idea if this `gopherjs tool` command is even supported, or what it's meant to do with all those flags. But this fixes the panic.
> Fix "shorthand redefinition" panic when running `gopherjs tool` command.

- compiler/natives/runtime/runtime.go
We fake a cgo environment to catch errors. Therefor we have to implement this and always return 0. 
Files compiled with `// +build cgo` can expect this even when not using any cgo.
> Implement runtime.NumCgoCall()

- build/build.go
- compiler/compiler.go
- compiler/package.go
- tool.go
Because of vendoring, there is no strict mapping between import path -> PackageData -> Archive any more. I'm trying to address the situation in this changeset. Might be related to #409. I'm still not entirely happy, but it improves the situation a bit.
@shurcooL PTAL. Hopefully your go tool project will enable us to throw away this code (or at least not use it in the gopherjs binary any more ... some parts could be kept in a separate library as a helper).
> Refactor build package

- README.md
Fixes #268.
The `gopherjs serve` command was originally added in https://github.com/gopherjs/gopherjs/issues/121, motivation and background can be found there.
> README: Document gopherjs serve command.

- build/build.go
The import path of this package has changed to github.com/fsnotify/fsnotify.
The old import path still works, but that was [an unplanned coincidence](https://github.com/fsnotify/fsnotify/issues/108#issuecomment-185815848). It is no longer officially supported.
See https://github.com/fsnotify/fsnotify/issues/118#issuecomment-185814855 and https://github.com/fsnotify/fsnotify/issues/108#issuecomment-185824561 for source. /cc @nathany
According to https://github.com/fsnotify/fsnotify#api-stability there are future API changes planned, but we can easily update our usage when that happens, so I don't think we need to vendor it at this time.
> build: Update dependency import path.

- compiler/natives/net/net.go
In Go's "net" package, some syscalls are invoked during initialisation. Since the JS runtime that GopherJS targets cannot make syscalls, these need to be mocked out with empty functions to prevent runtime errors.
To mock out a standard Go function so that the GopherJS compiler will provide a substitute function at compile time, you simply add the extra functions to : 
gopherjs/compiler/natives/package-name/filename.go
... and the compiler will then inject these "native" alternatives in the generated JS code. This makes it very simple to find where GopherJS is using overrides, and see exactly whats going on.
In the case of the "net" package, there are already some mocks for syscalls, such as probeIPv4Stack() and sysInit()
However, the "net" package init in Windows is different, and it …
> mock call to probeWindowsIPStack()

- compiler/natives/syscall/syscall.go
The real syscall package doesn't import bytes. This keeps the order in which stdlib packages must be built in for GopherJS consistent with the real standard library.
Source: https://godoc.org/syscall?imports
Helps #388.
> compiler/natives/syscall: Don't import bytes package.

- compiler/version_check.go
Be more strict in the version check, so it's clear which versions are supported. Only Go 1.6, 1.6.1, and 1.6.2, not older nor newer.
This should help communicate to people who try running GopherJS with tip and run into issues that it's because 1.6 strictly is required, rather than "1.6 and newer".
/cc @neelance I couldn't think of a reason not to this, but is there one? I've seen a few comments where people tried GopherJS with tip and it failed, so they had to use 1.6. I think we should be more explicit about that, especially now that 1.7 is getting nearer. The current `master` branch expects and supports 1.6 only, not newer. Thoughts?
Maybe we didn't have this sooner because it wasn't possible? `go1.7` build tag has only been added on March 7 in …
> compiler: Verify version Go 1.6 strictly, tip not supported.

- compiler/natives/fs.go
DO NOT MERGE until shurcooL/httpfs#4 is merged, since this change depends on that.
Rewrite filter in terms of `Keep` rather than `Skip` to make the logic simpler and more readable.
Tested locally with shurcooL/httpfs#4 merged (locally, not yet pushed upstream).
> compiler/natives: Update filter API.

- tool.go
It was initially added to support Go language tests. See https://github.com/gopherjs/gopherjs/commit/da075debc443510928caee184375aa76898c6d38#commitcomment-17247656.
Remove it since it's no longer needed, and it's unlikely to be used.
Helps #388.
In my local testing, `gopherjs test` still worked. [CI passes](https://circleci.com/gh/gopherjs/gopherjs/879) so that means standard library and language tests are working. If anyone knows of something that this breaks, please let me know.
> Remove tool command.

- tool.go
This adds support for the `TestMain` function in test mode, described [here](https://godoc.org/testing#hdr-Main), and requested in issue #239.  Naturally, I took inspiration from the relevant official [go source](https://github.com/golang/go/blob/master/src/cmd/go/test.go).
I have tested it to the extent I know to. It's possible I may have missed some functionality. Any other suggestions or feedback is welcome.
> Add support for TestMain function in test mode

- doc/packages.md
Followup to #454. Mention that Fetch API can be used.
Mention that only `net/http` client is supported, server is not.
Also mention that by default, without third party polyfill modules for XHR or Fetch APIs, node.js will not support net/http.
> doc: Update net/http notes.

- compiler/expressions.go
This fixes #374 for the case of `$`.
> Allow assignment to $

- build/build.go
- build/build_test.go
- compiler/natives/doc.go
Natives augment the standard library with GopherJS-specific changes. This test ensures that none of the standard library packages are modified in a way that adds imports which the original upstream standard library package does not already import. Doing that can increase generated output size or cause other unexpected issues (since the cmd/go tool does not know about these extra imports), so it's best to avoid it.
It checks all standard library packages. Each package is considered as a normal package, as a test package, and as an external test package.
Depends on #480 and #482 being merged. It catches both those issues, so the test will fail until those PRs are merged (and this branch is rebased).
> build: Add test to verify that augmented packages don't import extras.

- tool.go
This PR improves the usability of gopherjs in shell scripts by ensuring that a failure due to unknown command line flags results in a non-success exit code.
> Exits with non-success exit code upon root command failure

- tool.go
This fixes #239. It is a followup to #380, now that #381 is fixed to add support for executing example code along with tests.
I think this is complete, but I want to do some additional testing before declaring it so.
> Add support for executing examples

- build/build.go
- tool.go
This PR adds a simple command line flag to the gopherjs tools that configures how the sourcemaps are generated during a build.  When using the `--localmap` flag, the sourcemaps will use the original local disk location instead of the default behavior.
This improves the development experience when serving gopherjs compiled code off the local disk, such as, in my case running an electron app powered by gopherjs.
> Add support for source maps that use the local disk path of go source

- compiler/natives/src/net/http/fetch.go
Previously, it was not possible to call stream.cancel and block until a response was available, because of a bug in GopherJS that prevented blocking func calls from being deferred.
That bug has since been resolved in 50101461d59f26b13c876f57aab314ce55387671, so it's possible to do that now.
However, I found no compelling reason to do so at this time. I prefer not to implement this without a concrete reason and a way of testing that it works correctly, so simply update the comment and remove commented out code.
If a need comes up in the future, it can be implemented and tested then.
Do not regenerate because this change is a noop.
- https://fetch.spec.whatwg.org/
- https://streams.spec.whatwg.org/#readable-stream-cancel
> compiler/natives/src/net/http: Stay with ignored stream cancel error.

- README.md
GopherJS itself supports vendoring, but vendoring _it_ into your project is currently not supported. Issue #415 tracks the progress on fixing that.
Helps #415.
Updates #537.
/cc @jraedisch and @myitcv FYI.
> README: Document that using vendored GopherJS is currently not supported.

- README.md
Insert a missing newline tells the markdown parser to generate a header instead of just '####'. See current gopherjs page for reference.
> Add missing line spacing

- README.md
The google group for GopherJS has been deprecated (it's read-only now). It has bad UI, and it was used very infrequently. Messages posted there were often not seen for weeks by anyone. It's better to have them posted elsewhere.
Please use the issue tracker and slack channel instead.
> README: Remove google group link.

- build/build.go
- compiler/typesutil/typesutil.go
This follows #538.
Vendoring `github.com/gopherjs/gopherjs/js` package is not supported, and can cause hard to understand runtime errors. Better catch it earlier and print a clear error message.
Helps #569.
> build: Detect vendored js package and return error.

- compiler/utils.go
By supplying a value on both sides of the check, browsers are able to
always assume a value will exist (even if it is bypassed by the thrown
error), and optimize accordingly.
> Optimize bounds checking's ternary operator use

- compiler/compiler.go
- third_party/importer/export.go
- third_party/importer/import.go
- tool.go
This PR is a minor refactor (no behavior change) to simplify and clean up some of the code I've recently seen/looked over, and found opportunities to improve. Some of the changes are ones I wanted to make while working on #595, and some others I just did on the fly when making this PR.
Please review commit-by-commit. Each commit contains a readable bite-sized changed, and the commit message describes the motivation and rationale. Please leave comments if you disagree with something or have better suggestions.
There should not be any provable behavior changes. If there are, that's a bug.
> Minor refactor (no behavior change) to simplify and clean up.

- compiler/prelude/prelude.go
- js/js_test.go
- js/js_test.inc.js
- tests/deferblock_test.go
This PR should fix the problem mentioned in #597 .
Using this sample program:
package main
import "honnef.co/go/js/console"
func main() {
x := []byte{}
var y []byte
z := []byte{0x01}
console.Log(x)
console.Log(y)
console.Log(z)
}
Before:
[]
[]
Uint8Array [ 1 ]
After:
Uint8Array [  ]
Uint8Array [  ]
Uint8Array [ 1 ]
> Don't ignore array type for special JS array types

- tests/run.go
- tool.go
This reverts commit 62bca28b2835514b22712edb8104a624030a08c0.
We've originally discussed two possible fixes in issue #594:
> The gopherjs tool does not use the GOARCH environment variable
> in any way. Internally, GopherJS always uses js as GOARCH value
> when compiling user code, but it does other internal stuff when
> compiling standard library.
>
> 1. One fix is to make the gopherjs tool really ignore GOARCH env
> var. In other words, setting it to any value should have no effect;
> it shouldn't cause this failure.
>
> 2. We could also consider making it use the value of GOARCH, and
> error out if it's set to anything other than js (which is the
> default and the only supported value). Since gopherjs can't compile
> for any other architectures.
Upon further consideration, after seeing …
> Revert "Handle GOARCH env var similarly to cmd/go."

- js/js.go
When the "See GopherJS' README for details." phrase was added in 88f12aa6b316ade3347e7723510a954e09edff1d, the JavaScript <-> Go conversion table was in README. It was moved in c6e849f88527ab0a93f7d4ee4d9c67a65db5285c to the [package comment of `js` package](https://github.com/gopherjs/gopherjs/blob/3496c6f94e1b945f3fc9580f6982675c0a74cd6c/js/js.go#L5-L23).
Fixes #622.
> js: Point to new location of Interface conversion details.

- README.md
- tool.go
Be more specific that it's the source-map-support module that needs to be installed. Point to the instructions for source-map-support module installation.
Fixes #627.
/cc @slimsag Can you review this text? Do you think it's an improvement in readability over what you saw before?
> Improve "source maps disabled" warning text.

- compiler/prelude/jsmapping.go
I [noticed](https://github.com/shurcooL/backlog/issues/21#issue-159100785) that the code that does string internalization/externalization uses a regexp to detect if the string consists of ASCII characters only, in order to shortcut the conversion process.
Regexps are a general tool that optimizes for brevity, not performance. When inside a hot loops, it's often possible to write faster code rather than using a regexp.
I modified the prelude code as follows to gather some timing information:
```JavaScript
var regexpTaken = 0;
setInterval(function() {
console.log("regexpTaken: " + regexpTaken + " ms");
}, 3000);
```
```JavaScript
var t0 = performance.now();
var x = $isASCII(v);
var t1 = performance.now();
regexpTaken += t1 - t0;
```
I found that for most programs, the process of string …
> compiler/prelude: Optimize ASCII string detection.

- build/build.go
The parent scope `pkg` variable was inadvertently shadowed in #411. As a result, the value of `impModeTime` was wrong, and the if statement could never be true, and `pkg.SrcModTime` was never updated to a later time.
The shadow happened at https://github.com/gopherjs/gopherjs/commit/e3a9838fe85c461e4cd869da5065ea1f21b1759e#commitcomment-21940173.
Fixes #559 (possibly other similar issues, but they'll need to be verified).
> build: Fix shadowing bug in staleness calculation.

- tool.go
It's useful for running a benchmark multiple times, to get a better benchmark comparison.
Reference: https://golang.org/cmd/go/#hdr-Description_of_testing_flags.
> Add support for gopherjs test --count flag.

- build/build.go
The code is not easy to read, documenting the behavior helps a lot with readability.
Fix typo in `impModeTime` variable. "ModTime" stands for "modification time", so "e" doesn't belong.
> build: Document what packages are being ignored.

- build/build.go
- compiler/version_check.go
- tool.go
This change improves the `gopherjs build`, `gopherjs install`, `gopherjs test` commands to behave more like the equivalent `go` commands. Namely, while previously not possible, one can now:
- Use import path [patterns](https://golang.org/cmd/go/#hdr-Description_of_package_lists) when specifying packages:
```
gopherjs test github.com/user/repo/...
```
- Use relative import paths when specifying packages:
```
gopherjs test ./foo/bar
```
- Use relative patterns when specifying packages:
```
gopherjs test ./...
```
It also includes other minor improvements and simplifications to the code and behavior of the `gopherjs` tool.
The change is somewhat large, but broken up into 4 individual commits with detailed description in their commit message.
Fixes #302. /cc @slimsag FYI, since you recently …
> Add support to gopherjs tool for specifying import path patterns and relative import paths.

- compiler/expressions.go
- tests/misc_test.go
This PR fixes https://github.com/gopherjs/gopherjs/issues/649.
The problem was that a numeric expression like `float64(a - b) / c` was converted to `a - b / c` when `a -
b` was float64. This PR adds parenthesis to all numeric expressions at `fixNumber`.
I think there was a potential bug that `int(a - b) / c` was converted to `a - b >> 0 / c`, but I couldn't find a actual problematic case.
> Use parenthesis for numeric expressions

- circle.yml
- tool.go
~Waiting for the Go 1.9 branch to land first - DONE in https://github.com/gopherjs/gopherjs/pull/651~
Picking up on @shurcooL's comment in https://github.com/gopherjs/gopherjs/pull/669#issuecomment-325138883.
We've started randomly seeing std library tests tip over the V8 stack size limit, causing text/template TestMaxExecDepth to fail randomly locally and on CI. This had previously been addressed by @neelance in 1f89545; the `--stack_size` flag was passed to NodeJS which in turn passed the value onto V8. But per https://github.com/nodejs/node/issues/14567#issuecomment-319367412 it was pointed out that the value of `ulimit -s` must be `>=` the value of `--stack_size` for the `--stack_size` to make any sort of sense. Hence this commit also harmonises the setting of `ulimit -s` during the …
> build: unify setting of ulimit and stack_size

- internal/sysutil/sysutil.go
- internal/sysutil/sysutil_windows.go
- tool.go
Move the `syscall` use into an internal helper package, behind a non-Windows build constraint.
Also switch from `syscall` to `golang.org/x/sys/unix`, since `syscall` documentation recommends doing so.
Fixes #695.
> Fix build error on Windows due to syscall package.

- compiler/statements.go
- js/js_test.go
This brings the code emitted for a type switch with a `*js.Object`
case in line with the runtime `$assertType` function. In the case of
a `*js.Object` value, we have to dereference via `.$val.object`.
Fixes #682
> compiler: fix incorrect emitted Javascript for type switch

- compiler/prelude/jsmapping.go
This PR removes `canBlock` property from `$curGoroutine`, that is not used anywhere.
> Remove an unused local variable canBlock

- README.md
It might be confusing, so just use the example values and mention that the
`.js` file name comes from the directory name. Hopefully, this is more clear.
Updates #408.
/cc @baram204 Do you think this is easier to understand?
> README: Clarify {{base}} in gopherjs serve.

- build/build.go
- compiler/version_check.go
The proposal in golang/go#23172 was accepted. The "purego" build tag
is intended to be a community agreed upon soft-signal to indicate the
forbidden use of unsafe, assembly, or cgo.
Since GopherJS doesn't support those, it should always use "purego"
versions of Go packages when they're available. This is done by always
setting the "purego" build constraint.
Fixes #746.
> build: Add "purego" build tag to default context.

- internal/sysutil/sysutil.go
Trying to build [Perkeep](https://github.com/perkeep/perkeep) on FreeBSD:
```
➜ perkeep git:(master) go run make.go 
Now rebuilding gopherjs at /usr/home/juergen/perkeep/tmp/build-gopath-nosqlite/bin/gopherjs
error building gopherjs: error while building gopherjs: exit status 2, # perkeep.org/vendor/github.com/gopherjs/gopherjs/inter\
nal/sysutil
internal/sysutil/sysutil.go:12:10: cannot use r.Cur (type int64) as type uint64 in return argument
exit status 1
```
> internal/sysutil: Fix build error on FreeBSD due to Rlimit.Cur type mismatch.

- README.md
- doc/syscalls.md
Add instructions for what people should do when building with GopherJS on unsupported platforms. Code generation works completely fine, but syscalls (e.g., for `gopherjs run`) will only work on supported platforms.
Previously, this information was only in issues, people's heads, [commit messages](https://github.com/perkeep/perkeep/commit/749d51281d1f59617522b4fdd3acb5dac02683d6), etc. It should be documented in README to provide clarity.
Rename "OS X" to "macOS", the current name of that operating system. Rearrange sections to place more relevant information first. Mention Linux before macOS consistently. Linux is placed first because it's open source and more freely available than the proprietary macOS, so it's easier to recommend it as an alternative.
Resolves #770.
Updates #776. …
> README: Document supported GOOS values.

- compiler/vendor/golang.org/x/tools/go/gcimporter15/bexport.go
- compiler/vendor/golang.org/x/tools/go/gcimporter15/bimport.go
- compiler/vendor/golang.org/x/tools/go/gcimporter15/exportdata.go
- compiler/vendor/golang.org/x/tools/go/gcimporter15/gcimporter.go
- compiler/vendor/golang.org/x/tools/go/gcimporter15/isAlias18.go
- compiler/vendor/golang.org/x/tools/go/gcimporter15/isAlias19.go
As of 5dfd8930f264888dd5fe26820a0ac605a384dd33
golang.org/x/tools/go/gcimporter15 has been removed (in line with a
promise to remove this old API). This CL vendors a copy of
golang.org/x/tools/go/gcimporter15 as of
14d5b80f954f510ba9bcd241821b6f4828498e1a
(5dfd8930f264888dd5fe26820a0ac605a384dd33~1) minus *_test.go files and
the testdata directory (which contained binary files).
This is effectively a sticking plaster until we migrate, per the
deprecation notice, to golang.org/x/tools/go/gcexportdata.
Fixes #788
> compiler: vendor golang.org/x/tools/go/gcimporter15

- compiler/expressions.go
- compiler/statements.go
- compiler/utils.go
- js/js_test.go
Javascript allows for arbitrary strings to be used as index values on an
Object. A good example of where this comes up is React where `"data-*"`
and `"aria-*"` indexes are used on objects
(https://reactjs.org/docs/dom-elements.html). 
By switching from property selectors to the index operator (where required) we can support arbitrary string values in js-tagged fields for `*js.Object` special structs.
Fixes #778
> compiler: support arbitrary value js struct tag values

- tests/js_test.go
This way, all GopherJS-specific tests are in tests package, rather than
having an arbitrary split. None of the package js tests were internal
to the package.
This helps a future change where the js package becomes embedded into
the compiler. It makes it easier to add and modify GopherJS tests
without having to regenerate the js package.
Resolves #792.
> Move js package tests into tests package.

- circle.yml
- node-syscall/syscall.cc
We currently use [Node 6.2.2](https://github.com/gopherjs/gopherjs/blob/8dffc02ea1cb8398bb73f30424697c60fcf8d4c5/circle.yml#L3) in CI for our `gopherjs test` runs. 
Ever since the start of the Node 6.x series, `v8::Array::CloneElementAt` has been deprecated; here's an example from [our most recent `master` build](https://circleci.com/gh/gopherjs/gopherjs/1584):
```
make: Entering directory `/home/ubuntu/gopherjs/node-syscall/build'
CXX(target) Release/obj.target/syscall/syscall.o
../syscall.cc: In function ‘intptr_t toNative(v8::Local<v8::Value>)’:
../syscall.cc:28:51: warning: ‘v8::Local<v8::Object> v8::Array::CloneElementAt(uint32_t)’ is deprecated (declared at /home/ubuntu/.node-gyp/6.2.2/include/node/v8.h:3009): Cloning is not supported. [-Wdeprecated-declarations]
native[i] = …
```
> syscalls: move away from deprecated CloneElementAt

- tool.go
Added `<meta name="viewport" content="initial-scale=1">` for responsive web development environment with gopherjs via `gopherjs serve` command!
```html
<script defer src="`+base+`.js"></script>`
```
Added `defer` to execute the script as soon as the page load finished!
> Added viewport support and defered execution on gopherjs serve

- tool.go
This reverts commit bf5fc7d381404c2a218d4c28865b251d6e8e1cb8.
Reason: Discussion at https://github.com/gopherjs/gopherjs/pull/570#issuecomment-271660965
> Revert "Added viewport support and defered execution on gopherjs serve (#860)"

- circle.yml
- tests/run.go
So that we can then see the true diff that the Go 1.12 changes in
#900 will introduce.
> ci: upgrade to Go 1.11.5

- compiler/version_check.go
Introducing `syscall/js` (#899) is so significant that we update
the version.
> compiler: update version to 1.12-2

- circle.yml
This image is more standard and supported, unlike¹ the previous CircleCI-specific one.
¹ https://discuss.circleci.com/t/circleci-was-unable-to-run-the-job-runner/31894/18
Fixes #937
> CI: use ubuntu:18.04 image

- circle.yml
- tests/run.go
This change updates the CI script to test against Go 1.12.9¹, the latest minor release within the Go 1.12.x series. It updates the fixedbugs skip table accordingly.
¹ https://groups.google.com/d/msg/golang-announce/oeMaeUnkvVE/a49yvTLqAAAJ
> update to Go 1.12.9

- node-syscall/binding.gyp
- node-syscall/syscall.cc
- node-syscall/syscall_test.go
- tests/syscall_test.go
Some APIs were removed in Node 12, and new "safer" APIs must be used
instead. Perhaps this implementation is not the most elegant or produces
less then ideal error messages, but at least it compiles.
While at it, added an arena type to manage and gracefully free temporary
buffers we allocate for the duration of the call.
I couldn't find any tests for the syscall module, so I wrote a small
one.
Closes #935
> Fix up node-syscall to work with Node 12.

- circle.yml
This change updates the CI script to test against Go 1.12.16¹,
the latest minor release within the Go 1.12.x series.
¹ https://groups.google.com/d/msg/golang-announce/Hsw4mHYc470/WJeW5wguEgAJ
> update to Go 1.12.16

- build/build.go
- compiler/version_check.go
This is a possible fix for #969.  It seems like an ugly hack to me, but it solves the immediate problem.
> Build our own list of release tags

- build/build.go
- compiler/natives/src/internal/poll/fd_poll.go
- compiler/natives/src/internal/syscall/unix/unix.go
- compiler/natives/src/math/math.go
- compiler/natives/src/os/os.go
- compiler/natives/src/sync/pool.go
- compiler/natives/src/sync/sync.go
- compiler/natives/src/time/time.go
I'm slowly working towards making `gopherjs test` run. With this PR it is able to compile tests, but it fails at runtime because I haven't updated support reflectlite yet.
Packages covered in this PR:
- math
- sync
- time
- os
- internal/syscall/unix
Issue #989.
> Go1.16 support for several more stdlib packages

- .std_test_pkg_exclusions
- build/build.go
- compiler/natives/src/os/os.go
- compiler/natives/src/os/removeall_noat.go
- compiler/natives/src/testing/allocs_test.go
- compiler/natives/src/testing/helper_test.go
- compiler/natives/src/testing/sub_test.go
- compiler/natives/src/testing/testing.go
There were two major issues with the package:
- os.RemoveAll() implementation on linux was using Fstatat syscall,
which doesn't work with the node-syscall extension (see #993).
- runtime.Callers() is not implemented by GopherJS, which causes
testing package to report source code locations according to the JS
output file rather than the original Go code. I had to skip a bunch
of tests because of that, but at least most other tests can be
tracked now.
Updates #989.
> Support `testing` package with Go 1.16 and re-enable most of its tests.

- compiler/statements.go
- compiler/utils.go
- tests/lowlevel_test.go
- tests/testdata/defer_builtin.go
Because certain built-in function may not be translated into callable
expressions, GopherJS wraps them into a proxy lambda function when
necessary. Prior to this change it was incorrectly inferring argument
types for this proxy function, which led to a possible double implicit
type conversion and a runtime error in the generated code.
With this change, the types are assigned in accordance with what the
deferred function expects, and therefore no double conversion will
happen.
This change allows TesSliceNoCycle in `encoding/json` to pass under
Go 1.16.
Updates #989.
> Avoid double implicit type conversion on deferred built-in arguments.

- compiler/natives/src/syscall/js/js.go
This is an old addition that I've been using for a long time, maybe suitable to include in syscall
> compiler/natives/src/syscall: support copy bytes to/from js

- README.md
- compiler/expressions.go
- compiler/package.go
- compiler/statements.go
- compiler/utils.go
- compiler/version_check.go
- tests/misc_test.go
Upstream changes introduced in https://golang.org/cl/284052 introduced several new cases where `nil` identifier would be treated as untyped by `go/types` and an implicit type conversion would be expected. These changes future-proof GopherJS against this particular change.
I've also discovered an additional case, where untyped nil was causing a panic even with Go 1.16: `var _ *int = nil`, I fixed that as well.
I've manually tested these changes against Go `tip`: `go-tip install . && GOPHERJS_NO_VERSION_CHECK=true GOROOT="$(go-tip env GOROOT)" gopherjs test ./tests`.
This PR also includes a couple of changes that make debugging compiler panics and testing with unreleased versions a bit easier.
Fixes #1011.
> Future-proof untyped nil handling.

- build/build.go
- compiler/linkname.go
- compiler/natives/src/syscall/syscall_darwin.go
Changes in this commit ensure that we can at least build supported
standard library packages with GOOS=darwin. In theory, GOOS shouldn't
even matter, since we always target the same platform (nodejs or
browser), but for historical reasons, it does matter and we need to take
extra steps to make it work.
See https://github.com/gopherjs/gopherjs/issues/693 for more details.
Changes tested with `GOOS=darwin gopherjs build --minify -v $(go list std | grep -v -x -f .std_test_pkg_exclusions | grep -v -E "(vendor|internal)" | sort)`. Unfortunately, I don't have access to an Mac OS machine to run actual test… Ideally we should set up CI to do that.
Fixes #1023.
> Improve Mac OS (darwin) support.

- circle.yml
- compiler/version_check.go
This change is in preparation for a new release.
> Bump Go version to 1.16.5 and GopherJS version to 1.16.3+go1.16.5

- compiler/analysis/info.go
- compiler/astutil/astutil.go
This doesn't make any changes to the existing logic, but makes the code
a bit easier to read (or so I hope) and explains some of the logic I had
to reverse-engineer in the comments.
Overall this should make fixing
https://github.com/gopherjs/gopherjs/issues/603 a bit easier.
> Refactor the analysis package.

- compiler/analysis/info.go
- compiler/statements.go
- tests/goroutine_test.go
This change makes sure that whenever a function resumes execution after getting blocked by a deferred call, the return value is not lost. We do this by inserting a resumption point right before the return statement. If the return expression is not empty, we store it in a temporary variable to make sure it doesn't get evaluated twice.
> Fix undefined return when a deferred function blocks.

- build/build.go
There's no reason to set this tag as a special case for math/big only.
As far as I can tell, this tag isn't used anywhere else, and it should
be ok for us to set it just like "purego".
> Use make_big_pure_go build tag by default.

- build/build.go
- build/build_test.go
- build/cache.go
- build/context.go
- build/context_test.go
- build/fsutil.go
- build/versionhack/versionhack.go
- build/vfs.go
- circle.yml
- go.mod
- go.sum
- tests/gopherjsvendored_test.sh
- tests/misc_test.go
- tests/vendor/vendored/vendored.go
- tool.go
Fixes https://github.com/gopherjs/gopherjs/issues/855.
I took the approach of leveraging module support that's built into the `go/build` package. Doing so has two prerequisites:
1. `go/build.Context` instance must not have its file system methods overridden.
2. ReleaseTags must match the default.
Most of the changes in this PR tend to the #1. We were overriding FS access methods in order to make packages embedded in the VFS available during the build. Now we use two separate contexts chained together to access packages on the real FS and the embedded VFS. This refactoring is useful in the long run to make package loading logic more encapsulated in the build package.
The second prerequisite is somewhat bogus for reasons explained in the `build/versionhack` package. …
> Support Go Modules builds.

- build/build_test.go
- circle.yml
- doc/syscalls.md
- go.mod
- go.sum
- node-syscall/.gitignore
- node-syscall/index.js
- node-syscall/package-lock.json
- node-syscall/package.json
- package-lock.json
- package.json
- tests/gorepo/gorepo_test.go
- tests/gorepo/run.go
- tests/run.go
- tests/vendored_test.go
- tool.go
This PR contains a set of improvements and performance optimizations aimed shortening CircleCI runtime. Some of the most notable changes:
- `gopherjs test` can now execute tests for different packages in parallel, controlled by a `-p` flag.
- Go repository tests are now also run in parallel even when verbose mode is enabling. This allows us to better utilize 2 vCPU machines we get from CircleCI.
- Test results are now captured and exported to CircleCI, which should allow us to see individual test failures in its UI.
- Long-running tests (stdlib and gorepo) are split into separate jobs and are sharded into 4 parallel containers, balanced by the historical run time.
As an added bonus I've simplified how we install node.js dependencies, which is now as easy as `npm install`. I've also …
> Improve GopherJS CI run time and configuration

- circle.yml
- compiler/version_check.go
This PR has two trivial changes:
- Increment GopherJS patch version.
- Update Go version we test against to the latest 1.16.x release (1.16.7).
Even though this release has a substantial new feature, which is Go modules support, we decided to make this a patch-level release to keep minor versions of Go and GopherJS in sync, which would be perhaps a bit less confusing.
I also cherry-picked a CircleCI change from the 1.17 WIP branch that should reduce test flakiness due to no-output timeouts.
> Prepare for a new GopherJS release.

- compiler/package.go
This allows sourcemap to be generated for top-level variable
declarations with initializer, for example:
```go
var x = initX() // Might panic.
```
This is particularly helpful when debugging panics in such initializers.
> Preserve position information for top-level variable declarations.

- compiler/astutil/astutil.go
- compiler/astutil/astutil_test.go
- compiler/package.go
- compiler/statements.go
- compiler/utils.go
This PR prevents GopherJS compiler from emitting unnecessary control statements in two cases:
1. A redundant return at the end of a function, which already has a return statement at the end, but this statement is wrapped into another AST element.
2. A redundant instruction to go to the beginning of a flattened loop, in case the last statement of the loop is a return or unconditional branching statement (break, continue, goto).
The change is mostly cosmetic and prevents Firefox from spamming "unreachable code" warnings, which can be confusing to GopherJS users. It also marginally reduces the size of the generated code, but the effect is so small that it doesn't really matter.
Fixed #575, #1069.
> Fix two classes of "unreachable code" warnings in Firefox.

- compiler/analysis/info.go
Such functions are usually subjects of a go:linkname directive, which
imports function body implementation from elsewhere. Without getting
deeper into analyzing directives, we can conservatively assume the
function is blocking.
> Assume all functions without body are blocking.

- tests/slice_to_array_ptr_test.go
Some of the tests that were expecting a panic were using a function
literal, but instead of calling it and comparing the result to nil, they
were comparing the function itself.
This change refactors the test to make such a mistake less likely in
future.
Kudos to @dominikh for spotting the bug!
> Fix a typo in slice-to-array conversion tests.

- tool.go
Buffering is already disabled when -p=1, which allows to see test output
in real time. With this change it will be done automatically if only one
package matched.
> Disable test output buffering when testing only one package.

- compiler/expressions.go
- compiler/statements.go
- compiler/utils.go
- tests/goroutine_test.go
Built-ins and `js.Object` methods are represented by JS expressions that may not be straightforward function calls, or reference functions defined in the prelude. In such cases, the callable expression must be wrapped in a lambda.
#998 has fixed a similar issue for the `defer` keyword, and this change generalizes the same fix for the `go` keyword.
This change also contains a small improvement to the compiler panic message, which makes it easier to read at-a-glance.
Fixes #547.
> Correctly handle built-ins and `js.Object` methods with go keyword.

- js/js.go
Fixes https://github.com/gopherjs/gopherjs/issues/1094.
> Clarify in which runtimes `js.Module` variable is available.

- compiler/utils.go
- tests/compiler_test.go
This PR is simply a rebase of #807 plus a small patch to work with a modern version of GopherJS.
Fixes #806
> compiler: fix variadic args not being nil when zero length.

- tool.go
Currently the developer running on Windows should use `set GOOS=linux` and then run the `gopherjs`. Have some issues about it: https://github.com/gopherjs/gopherjs/issues/875, https://github.com/gopherjs/gopherjs/issues/776.
This changes makes the `gopherjs` to use the `GOOS=linux`, clearly telling that the GOOS was changed, the user can still use the `GOOS=darwin` or `GOOS=linux` manually.
The README says:
> gopherjs uses your platform's default GOOS value when generating code. Supported GOOS values are: linux, darwin. If you're on a different platform (e.g., Windows or FreeBSD), you'll need to set the GOOS environment variable to a supported value. For example, GOOS=linux gopherjs build [package].
This change makes the gopherjs use the `GOOS=linux` by default on any unsupported GOOS and …
> Detect unsupported GOOS

- build/build.go
- build/context.go
This PR contains several relatively minor refactoring within the `build` package, which set the foundation for bigger improvements I'm working on. It includes the following:
- golint warning fixes in the package.
- Removal of an unused BuildDir function. I did a search across GitHub and it doesn't seem to be used anywhere outside of our repo either.
- Moved tweaks to files included into stdlib packages inside the simpleContext type. This puts pre- and post-load tweaks in the same logical place and fixes a bug where such tweaks weren't applied in some code paths.
- Update loaded package's import lists to exclude dependencies from the excluded files. This doesn't fix any bugs per se, but it makes the API slightly less error-prone.
Since these changes are relatively self-contained and the …
> Build package cleanups and minor improvements

- compiler/statements.go
- tests/goroutine_test.go
In almost every place compiler checks whether a function is blocking by
checking `len(c.Blocking) > 0`, so assigning false to the map confuses
the check, causing unnecessary checkpointing prologue and epilogue to be
added to the function.
Fixes https://github.com/gopherjs/gopherjs/issues/1106.
> Prevent non-blocking select from making function appear blocking.

- build/build.go
- build/cache/cache.go
- compiler/gopherjspkg/fs.go
- compiler/natives/fs.go
- go.mod
- go.sum
- tool.go
- Optional logging of build cache use and errors.
- `gopherjs clean` command to clear the entire cache.
- `-a` flag to force a clean  rebuild for the specified targets, but without the complete cache erasure.
> Quality of life improvements for build cache

- compiler/analysis/info.go
- compiler/analysis/info_test.go
- compiler/astutil/astutil_test.go
- internal/srctesting/srctesting.go
When a function literal is used that calls another function and that other function has yet to be analyzed, the call site for the function literal is not retained, so it's not processed later, so the function that was calling the function literal is not made blocking itself, when it should be.
This change makes blocking status propagate through any number of intermediate literal function calls.
This is a rebase of https://github.com/gopherjs/gopherjs/pull/956 with additional regression tests.
Fixes https://github.com/gopherjs/gopherjs/issues/955.
> Propagate blocking function information through function literal calls.

- compiler/natives/src/syscall/fs_js.go
The first fix is also present upstream: see [js_fs.go](https://github.com/golang/go/blob/master/src/syscall/fs_js.go#L504). According to the comment, it is here because Node.js 8 `fs.utimes()` can call the callback without arguments.
The first fix also protects against the [BrowserFS](https://github.com/jvilk/BrowserFS) project’s almost 50 code locations where a callback is called without arguments:
- [SynchronousFileSystem.rename()](https://github.com/jvilk/BrowserFS/blob/master/src/core/file_system.ts#L806)
- [PreloadFile.close()](https://github.com/jvilk/BrowserFS/blob/master/src/generic/preload_file.ts#L143)
- [DropboxFileSystem.rename()](https://github.com/jvilk/BrowserFS/blob/master/src/backend/Dropbox.ts#L298)…
The second commit is an additional safety against the callback argument …
> Fix jsFS callback-related crashes

- README.md
GopherJS gained support for building code in module mode in 2021 (see PR #1042), and it itself didn't have problems being built in module mode since much earlier.
Recently, it started getting semver tags that are recognized in module mode like `v1.17.2` and `v1.18.0-beta1` (see issue #847). Start suggesting the `go install` command to install its latest release in the README.
(It remains possible to get the latest development version with something like `go install github.com/gopherjs/gopherjs@HEAD`, or one of the pre-release versions from `go list -m -versions` such as `go install github.com/gopherjs/gopherjs@v1.18.0-beta1`.)
While here, also update to the new shorter Go website domain and latest Go 1.18 point release.
> README: suggest go install for installing

- compiler/utils.go
- tests/compiler_test.go
Previously we would pass an empty slice, which is against the Go spec:
> If f is invoked with no actual arguments for p, the value passed to p is nil.
Source: https://go.dev/ref/spec#Passing_arguments_to_..._parameters
Fixes https://github.com/gopherjs/gopherjs/issues/1147
> Pass nil slice when variadic arguments are omitted after regular args.

- compiler/package.go
- compiler/statements.go
- compiler/utils.go
A couple of minor refactorings to make generics-related work a bit easier:
- Add comments for all `functionContext` fields. Some of these could be improved, but I am not familiar enough to do that.
- Make use of the utility `signatureTypes` type in the `functionContext`, which enables more self-descriptive conditions in the code. This type will be further expanded with generics-specific utilities in later commits.
- Minor improvements to the indentation-related methods.
> Comments and readability improvements for the functionContext type.

- compiler/natives/src/reflect/reflect.go
- tests/linkname_test.go
compiler/natives/src/reflect for compatible go reflect
- newName => resolveReflectName 
- uncommonType can be set
> compiler/natives/src/reflect: compatible go reflect

- compiler/natives/src/syscall/js/js.go
Minor tweak to `syscall/js` to follow a security best practice as advised by MDN:
[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#never_use_eval!](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#never_use_eval!)
> Additionally, modern JavaScript interpreters convert JavaScript to machine code. This means that any concept of variable naming gets obliterated. Thus, any use of eval() will force the browser to do long expensive variable name lookups to figure out where the variable exists in the machine code and set its value. Additionally, new things can be introduced to that variable through eval() such as changing the type of that variable, forcing the browser to re-evaluate all of the generated machine code to …
> Replacing eval() calls in syscall/js

- compiler/natives/src/reflect/reflect.go
- tests/misc_test.go
fix https://github.com/gopherjs/gopherjs/issues/1163 reflect.Value.Set for struct by flagIndir
> compiler/natives/src/reflect: fix reflect.Value.Set kind Struct by flagIndir

- compiler/expressions.go
- compiler/package.go
- compiler/statements.go
- compiler/utils.go
Instead of generating an independent function instance for every combination of type parameters at compile time we construct generic function instances at runtime using "generic factory functions". Such a factory takes type params as arguments and returns a concrete instance of the function for the given type params (type param values are captured by the returned function as a closure and can be used as necessary).
Here is an abbreviated example of how a generic function is compiled and called:
```
// Go:
func F[T any](t T) {}
f(1)
// JS:
F = function(T){ return function(t) {}; };
F($Int)(1);
```
This approach minimizes the size of the generated JS source, which is critical for the client-side use case, at the cost of runtime
performance. See …
> Rudimentary support for passing type parameters into generic functions

- compiler/package.go
- compiler/typesutil/typesutil.go
- compiler/typesutil/typesutil_test.go
- compiler/utils.go
Instead of being initialized at the package level, they are initialized inside a generic factory, where type params are available.
Example:
```
// Go:
func _F[T any](t T) {
_ = []T{}
}
// JS:
_F = function(T){
var sliceType = $sliceType(T);
return function(t) {
$unused(new sliceType([]));
};
};
```
Updates #1013.
> Initialize type param-dependent types in a generic factory function.

- compiler/expressions.go
- compiler/package.go
- compiler/utils.go
- tests/gorepo/run.go
- Fix gorepo test runner to handle another variant of the `-gcflags="-G=3"` flag.
- Correctly return `varFuncLocal` declaration level for JS variables corresponding to local variables.
- Correctly zero-initialize variables of generic types.
Updates #1013
> Several small fixes to generics handling

- compiler/package.go
- tests/typeparams/blocking_test.go
Previously it was incorrectly returning a reference to the generic factory function. With this change it correctly returns a reference to the generic function instance.
Updates #1013
/cc @paralin
> Fix incorrect continuation callback for a blocking generic function.

- compiler/compiler.go
- compiler/errors.go
- compiler/linkname.go
- compiler/package.go
- compiler/sources.go
This is the first step in reducing complexity of the compiler.Compile function.
The new `sources` type represents all inputs into the package compilation and simplifies extracting useful information out of them. It is designed to have little business logic of its own and serves as a convenient bridge to other packages like go/types or astrewrite.
The ErrorList type is extended with utility methods that reduce verbosity of the calling code.
/cc @paralin
> compiler: factor out utility types for processing Go sources and errors.

- README.md
- doc/compatibility.md
GopherJS 1.18 has standardized on a single value for GOOS and GOARCH in PR #1111. Update the README accordingly. (There has been agreement in issue #1169 that it's okay to be updating the top-level README for GopherJS 1.18-specific changes by now.)
Also reword advice in compatibility.md to be more general. The upstream Go WebAssembly port (i.e., GOOS=js GOARCH=wasm, and notably not wasm64) is limited to 4 GiB of linear memory (at least [for now](https://github.com/WebAssembly/memory64/blob/d0fbbe7b1d3c2cabf8409a48f70c94956ebfbe7f/proposals/memory64/Overview.md)), it just [happens to](https://github.com/golang/go/issues/18892#issuecomment-341889653) at this time use 64-bit variables for int/uint/uintptr types. So maybe it's not a great example to refer to. But a reminder that some types …
> README: document the current GOOS and GOARCH values

- compiler/astutil/astutil.go
Turns out, for a method like `func (v *value[T]) get() T {...}` first `*ast.StarExpr` is unwrapped and then `*ast.IndexExpr`. Using a type-switch allows only one of them to be unwrapped.
I also enabled branch protection on the generics branch to catch this type of issue before merge.
> Replace type-switch with a sequence of ifs.

- compiler/natives/src/runtime/runtime.go
- compiler/natives/src/syscall/syscall_js_wasm.go
These changes make gopherjs work correctly in environments with fake `$global.process` object, which may be missing some of the properties. Specifically, when Go's `wasm_exec.js` is used, it fakes that object, but only partially. So if a gopherjs program was loaded in the same context as a Go wasm program, gopherjs would throw an undefined property exception.
> Additional nil checks around NodeJS APIs.

- compiler/expressions.go
- compiler/functions.go
- compiler/package.go
- compiler/utils.go
This PR contains several commits that split up the two giant `translateTopLevelFunction()` and `translateFunction()` functions into more manageable pieces. Where possible I tried to add explanations for subtle and non-obvious aspects of the code - to the best of my ability to infer them (largely through breaking them and observing the results).
This refactoring should be functionally-neutral.
/cc @paralin 
Updates #1013.
> Refactoring and readability improvements to function/method generation code

- compiler/expressions.go
- compiler/functions.go
- compiler/natives/src/reflect/reflect.go
- compiler/package.go
- compiler/utils.go
The main change is that we assign explicit names to all function objects that correspond to Go functions (named and literals). Function name is declared as `var f = function nameHere() { ... }` and is visible inside the function scope only. Doing so serves two purposes:
- It is an identifier which we can use when saving state of a blocked function to know which function to call upon resumption.
- It shows up in the stack trace, which helps distinguish similarly-named functions. For methods, we include the receiver type in the identifier to make A.String and B.String easily distinguishable.
The main trick is that we synthesize names for the function literals, which are anonymous as far as go/types is concerned. The upstream Go compiler does something very similar.
Lest but not least, with …
> Assign identity to all function literals and use them as funcRefs.

- compiler/expressions.go
- compiler/statements.go
- tests/misc_test.go
- When converting between pointers to structs, gopherjs incorrectly used underlying type as a conversion target.
- Assignment operator didn't handle implicit type conversion between named and anonymous types.
> Fix two bugs related to type conversion

- tests/gorepo/run.go
Also pick up more advanced run args parsing from the upstream to better deal with -gcflags flag.
> Diagnose some of the typeparam test failures.

- compiler/expressions.go
- compiler/utils.go
- tests/misc_test.go
Prior to this change, the following code would panic the compiler:
```go
type (
S  struct{ f int }
PS *[]S
)
var _ = []*S{{}} // This compiles, but potentially incorrectly.
var _ = []PS{{}} // Compiler panics here.
```
Prior to this change, GopherJS compiler didn't expect that a pointer type could be named in this context, and would panic. This is addressed by checking the underlying type, rather than the type itself.
However, there was a bigger correctness problem here too. According to the Go spec:
> Within a composite literal of array, slice, or map type T, elements or map keys that are themselves composite literals may elide the respective literal type if it is identical to the element or key type of T. Similarly, elements or keys that are addresses of composite literals may elide the …
> Fix compiler panic when handling composite literals representing named pointer types.

- compiler/prelude/goroutines.js
- compiler/prelude/jsmapping.js
- compiler/prelude/numeric.js
- compiler/prelude/prelude.js
- compiler/prelude/types.js
This is done with the help of [lebab](https://github.com/lebab/lebab).  More transformations could be done. In particular, by using `let` and `const`, instead of `var`, we can safely do a number of other conversions, however, this tool is not able to safely do the let/const conversion automatically, so we should probably do (or at least validate) that manually.
> Perform a few automated ES6 transformations to our prelude

- build/build.go
- compiler/astutil/astutil.go
- compiler/natives/src/regexp/regexp_test.go
Rebase of #798, and applied change suggested in https://github.com/gopherjs/gopherjs/pull/798#issuecomment-955238429, and a couple cleanups.
> Ability to call overridden functions from the std library

- compiler/astutil/astutil.go
- compiler/expressions.go
- compiler/filter/assign.go
- compiler/prelude/types.js
- compiler/typesutil/coretype.go
- compiler/utils.go
- tests/gorepo/run.go
- Fix a compiler panic caused by composite literals like `T{f: 1}` where `T` is a type param.
- Fix address taking of an array/slice element where the array is element type is a type param and the concrete type is a struct.
- Reclassify one of the test failures as unrelated to generics, since it uses unsafe if ways we don't support.
While at it, make a few small refactorings of the AST utility methods.
See commit messages for the detailed information. At this point all remaining typeparam test failures seem to be related to unimplemented features rather than bugs.
Updates #1013
> Fix a few outstanding bugs in generics handling

- compiler/natives/src/reflect/reflect.go
add func name.setPkgPath 
this a way for enable hack reflect set type pkgPath. <https://github.com/goplus/reflectx>
> compiler/natives/src/reflect: add func name.setPkgPath

- circle.yml
Some recent PRs have failed, apparently due to CircleCI dropping support for the old version of xcode we were using.  This bumps up to the oldest version currently supported. Maybe we want something much newer, but as a non-Mac user, I'm not really sure what that might entail, so making the most conservitive change possible.
> Bump xcode version used in CI

- compiler/natives/src/golang.org/x/crypto/internal/alias/alias.go
- compiler/natives/src/golang.org/x/crypto/internal/subtle/aliasing.go
Same as fcd349a8b55efd1bb45c715624591e75dd237138.
x/crypto internally moved the AnyOverlap from
x/crypto/internal/subtle/ to /x/crypto/internal/alias/.
> natives: duplicate aliasing.go in x/crypto revisted

- compiler/prelude/jsmapping.js
- tests/js_test.go
This PR adds code that maps JavaScript object fields to Go struct fields.
Updated the $kindStruct case with a loop to dynamically map JavaScript object fields to corresponding Go struct fields.
Stuff I've tested,
possibly fixes #975
> support internalising structs

- build/context.go
```console
$ GOPHERJS_GOROOT="$(go1.18.10 env GOROOT)" gopherjs build
failed to expand patterns []: failed to list packages in the primary context: failed to list packages on FS: go tool error: /home/makki/Development/go/bin/go list -e -compiler=gc -tags=netgo,purego,math_big_pure_go,gopherjs -installsuffix= -f={{.ImportPath}} --: exit status 1
go: updates to go.mod needed; to update it:
go mod tidy
```
This error occurred when the built module targets a version earlier than go 1.21.0 in go.mod, while the imported package targets go 1.21.0.
In such cases, go 1.21.0 requires us to run `go mod tidy`, which was not required in previous versions of go.
Please see the example for detail: [github.com/makiuchi-d/gopherjs-fail-example](/makiuchi-d/gopherjs-fail-example)
In the GopherJS build …
> Avoid build failures with Go 1.21.0 installed in the environment.

- circle.yml
- nosync/mutex.go
- tests/misc_test.go
fix build for golang.org/x/tools/internal/tokeninternal
```
// require golang.org/x/tools v0.12.1-0.20230901210945-21090a2aa8d3
package main
import (
_ "golang.org/x/tools/go/gcexportdata"
)
func main() {
}
```
dump error
```
../../../go/pkg/mod/golang.org/x/tools@v0.12.1-0.20230901210945-21090a2aa8d3/internal/tokeninternal/tokeninternal.go:78:9: invalid array length -delta
* delta (constant -64 of type int64)
```
fixed:
Full in size nosync.RWMutex => sync.RWMutex
> nosync: fix build for golang.org/x/tools/internal/tokeninternal

- compiler/version_check.go
As of Go 1.21, the VERSION file has additional metadata after the first line.
Use only the text on the first line when reporting the Go version.
For #1018.
> compiler: discard metadata in VERSION file

- compiler/utils.go
- tests/typeparams/low_level_test.go
Prior to this change we always canonicalized method's type parameter names to their receiver counterparts. This was mainly necessary to avoid errors when we needed to reference method's type parameters inside a type generic factory function, e.g. when initializing method's reflection metadata.
Such implementation, however, was causing a bug when minification is enabled:
1. Methods are compiled first, variable names are allocated to their type parameters and the association is stored in the package context.
2. The allocated variable name is marked as in use within the mathod's functionContext, up to the enclosing generic factory function context, but not at the package level.
3. Type definitions are compiled second. Because the type's typeparams are already associated with variable names, …
> Fix minified variable name collision in a type generic factory function.

- compiler/natives/src/reflect/reflect.go
- tests/misc_test.go
In https://github.com/golang/go/issues/63886 it was pointed out that DeepEqual doc says: "Values of distinct types are never deeply equal", so the existing behavior is, in fact, correct even if somewhat surprising.
This reverts commit b66fa5779288949531caaf13f9d4e75e3e02e010.
#1013
> Revert "reflect.DeepEquals: channels of the same underlying type can be equal."

- compiler/expressions.go
- compiler/prelude/types.js
- compiler/utils.go
- tests/gorepo/run.go
- tests/typeparams/builtins_test.go
For many built-ins the behavior differs depending on their argument types. In such cases, each relevant type constructor has a method implementing the built-in for that specific type, e.g. for a slice `t` of type `T`, expression `len(t)` will translate into something like `T.$len(t)`. In some cases, where it doesn't seem performance-critical, I changed the whole implementation of the built-in to use this mechanism, even if no type parameters are involved to reduce the amount of duplicated logic.
Some functions like `append()` or `delete()` put sufficiently strict constraints on the type parameter to not require runtime dispatch. In those cases I only had to tweak the code a bit to correctly identify types.
Updates #1013.
> Add type parameter support for built-in functions.

- compiler/natives/src/internal/reflectlite/reflectlite.go
- compiler/natives/src/reflect/reflect.go
I updated the reflect and reflectlite package to set the embedded flag as part of the Go 1.19 upgrade.
Commit [e1e66a0 "move embedded bit from offset to name"](https://go-review.googlesource.com/c/go/+/412138) changes how reflect and reflectlite store the embedded flag. The creation of the `name` and the creation for `structField` is affected by this change for Go 1.19. Both are overwritten by GopherJS.
> v1.19 - Moving embedded bit from offset to name in reflect and reflectlite

- compiler/natives/src/net/http/http.go
- compiler/natives/src/reflect/reflect.go
- go.mod
- go.sum
- tests/gorepo/run.go
- tests/js_test.go
- tests/lowlevel_test.go
- tests/syscall_test.go
- tool.go
Two changes to go1.19:
- Reflect fix: Since go1.19 is hitting CI issues from the missing generics, this copy/paste mistake wasn't caught until further testing against the generics branch.
- Merge master changes
> go1.19: Fix reflect

- build/build.go
- compiler/astutil/astutil.go
- compiler/astutil/astutil_test.go
- compiler/natives/src/net/http/http.go
This ticket fixes the issue generics was causing in `parseAndAugment`. The problem was that `FuncKey` didn't handle `*ast.IndexListExpr` nor `*ast.IndexExpr` since those were introduced in function names for generics. This ticket has the following changes:
- Update FuncKey to handle generics.
- `compiler/natives/src/net/http/http.go` imports `io/util` which is no longer used in original runtime so causes the "extra import tests" in `build_test.go` to fail, so I also updated it to use `io`.
- Minor lint fix for creating an error.
> Update FuncKey to handle generics

- compiler/astutil/astutil.go
- compiler/astutil/astutil_test.go
- internal/srctesting/srctesting.go
This ticket extends how the directives are determined by allowing any AST node containing a comment able to be checked. This includes imports, functions, types, fields, and values.
This does not affect `//gopherjs:prune-original` and `//gopherjs:keep-original`, so currently we are still only checking for directives on functions. This change is in preparation for adding the `//gopherjs:purge` directive.
The only functional change should be that the directives are no longer prefix tested, meaning if there was a directive like `//gopherjs:keep-original-and-remove-overlay` we wouldn't accidentally match it to `//gopherjs:keep-original`. This is not currently a problem and will not affect the current code. This is just prevention of a potential problem as the directives are being worked on in …
> Extending directive checking

- build/build.go
- build/build_test.go
- compiler/astutil/astutil.go
- compiler/astutil/astutil_test.go
After a conversation with Nevkontakte ([here](https://gophers.slack.com/archives/C039C0R2T/p1701798056129639)), the current goal is to make go1.19 support without generics possible by dropping generic code. To accomplish this, I'm adding a new directive, `gopherjs:purge`, which will remove parts of the original code without replacing them with something in the overlay/override code. The native code will have the directive for some declaration or specification identifier and both the overlay and original will have that decl/spec removed from it.
This will allow us, in a follow up ticket, to add things into the natives that we want to remove, e.g. `type Pointer[T any] struct {}` in atomic. This will also help with imports for variable type constraints, e.g. `type Foo[T cmp.Ordered](value …
> Add purge directive

- compiler/analysis/info.go
- compiler/expressions.go
- compiler/package.go
- compiler/statements.go
- compiler/utils.go
Some generalized updates to the compiler as we head towards go1.19. `NewSignature` and `NewInterface` are deprecates for `NewSignatureType` and `NewInterfaceType`; update those deprecated methods. Add some more checks for generics and type parameters. Fixing some lint too.
> [go1.19] Update compiler

- build/build.go
- build/build_test.go
- compiler/astutil/astutil.go
- doc/pargma.md
- The build updates changes I did will still remove imports which are needed by directive only (i.e. `unsafe` for `go:linkname` and `embed` for `go:embed`). These directives are also read from the top-level comments by the compiler so we may not simply clear out the top-level comments.
- The import remover also had to deal with files like [src/math/rand/race_test.go](https://cs.opensource.google/go/go/+/refs/tags/go1.19.13:src/math/rand/race_test.go) which has a dot import (`	import . "math/rand"`). Typically we leave dot imports alone because it is hard to determine if they are used or not, however in this case, the test is removed making the import unused. So now, if the file is empty of anything but imports or the `go:linkname` directive (we don't have to worry about the `embed` since …
> [go1.19] Fix build issue and add override signature directive

- compiler/natives/src/crypto/elliptic/nistec.go
- compiler/natives/src/crypto/internal/boring/bbig/big.go
- compiler/natives/src/crypto/internal/nistec/nistec_test.go
- compiler/natives/src/crypto/internal/nistec/wrapper.go
- compiler/natives/src/go/token/position.go
- compiler/natives/src/hash/maphash/maphash.go
- compiler/natives/src/runtime/runtime.go
- compiler/natives/src/sync/atomic/atomic.go
- compiler/natives/src/sync/atomic/atomic_test.go
- compiler/natives/src/sync/sync.go
- compiler/natives/src/testing/helper_test.go
- compiler/natives/src/testing/helperfuncs_test.go
This is the updates to the native overrides to remove type parameters from the standard libraries as part of the generic-less go1.19.
There is more to still be done for natives, this just is part of the whole update. More will come later as we work our way through all the tests.
- This code uses the new directive, `gopherjs:override-signature` so won't function until #1260 has been merged into `go1.19`.
> [go1.19] Updating natives

- build/build.go
- build/build_test.go
- circle.yml
- tests/gorepo/run.go
This PR has three changes:
1. Fixed a problem when removing/keeping imports in the parse and augment phase. The problem comes from when a file imports something without using the blank (`_`) name (e.g. `import "unsafe"` or `import us "unsafe"`) , then augmentation removes all usages of that import except for one or more directives (e.g. `//go:linkname`). In this case leaving the import as is will cause an "unused import" error but removing the import will result in a "directive X needs import Y" error. To solve this I made this specific case change the name of the import to be a blank import (e.g. `import _ "unsafe"`).
2. Chocolatey doesn't have go1.19.13 so the Windows CI fails. I changed the Chocolatey to the nearest version it defines, go1.19.9. This fixes the problems for the Windows' …
> [go1.19] Known fails and build issues fix

- compiler/natives/src/crypto/internal/boring/bcache/cache.go
- compiler/natives/src/crypto/internal/boring/bcache/cache_test.go
- compiler/natives/src/crypto/internal/boring/sig/sig.go
- compiler/natives/src/crypto/internal/nistec/nistec_test.go
- compiler/natives/src/debug/pe/symbol.go
- compiler/natives/src/go/token/position.go
- compiler/natives/src/hash/maphash/maphash.go
- compiler/natives/src/internal/reflectlite/all_test.go
- compiler/natives/src/net/fastrand.go
- compiler/natives/src/net/netip/export_test.go
- compiler/natives/src/net/netip/fuzz_test.go
- compiler/natives/src/net/netip/netip.go
- compiler/natives/src/net/netip/netip_test.go
- compiler/natives/src/reflect/reflect.go
- compiler/natives/src/reflect/reflect_test.go
- compiler/natives/src/runtime/fastrand.go
- compiler/natives/src/sync/atomic/atomic_test.go
- compiler/natives/src/syscall/js/export_test.go
- compiler/natives/src/syscall/js/js_test.go
Updating more natives for go1.19 without generics:
1. Updated `crypto`: It had a copy/paste issue and had to remove the cache. The cache hooks into the GC to clear periodically. I wasn't sure if there was a JS equivalent or if we wanted to use a timer, so I just removed the cache, and now it is treated as if it was always a cache miss.
2. Added fix for `debug/pe`: It had some unsafe pointers for casting one struct into another struct's memory footprint.
3. Updated `go/token/position`: Was getting issues with finding most recent file so changed the fix to use `*File` directly.
4. Updated `hash/maphash`: It had parts from go1.16 which could be updated to match closer to go1.19. It had some new methods, `Bytes` and `String`, that were using unsafe pointer.
5. Updated `reflect` and …
> [go1.19] Updating more natives for go1.19

- circle.yml
- compiler/natives/src/crypto/internal/boring/bbig/big.go
- compiler/natives/src/crypto/internal/nistec/nistec_test.go
For some reason I was getting a failure from Chocolatey which wasn't happening before.
From `windows_smoke` step `Install Go`:
```Plain
Failures
- golang - A newer version of golang (v1.21.1) is already installed.
Use --allow-downgrade or --force to attempt to install older versions.
go version go1.21.1 windows/amd64
```
- I added a force and a confirmation to run the go1.19.9 script to fix this.
- I also ran go formatting to fix some issues in formatting
> [go1.19] Fixed chocolatey go version

- build/build.go
- build/build_test.go
The part of augmentation that prunes imports based on usage was designed to handle removing imports specific to a type parameter. For example, the import `cmp` might only exist in a file because of the type parameter constraint `cmp.Ordered`. Go doesn't like it if there are unused imports.
However, the code written for pruning imports uses the given name or guesses at the package name via the given path. This does not work for any relative paths (e.g. `./..`), versioned packages (e.g. `github.com/foo/bar/v2` where the package is `bar`), or using the `go.mod` to define a path for one package to an arbitrary path using a `replace`. These problematic paths do not exist in the natives which are being altered by augmentation, but problematic paths may exist in customer code.
Since we only …
> [go1.19] Limit augmentation to native files which need it

- .github/workflows/lint.yaml
- .github/workflows/measure-size.yml
- README.md
- circle.yml
- compiler/version_check.go
- go.mod
Updating the versions from go1.19.13 to go1.20.14.
go1.20.14 is the most recent update to go1.20 (released 2024-02-06)
⚠️ This will break CI via changes in the natives using generics and unsafe pointers
> [go1.20] Starting 1.20 updates

- build/build_test.go
- compiler/analysis/info_test.go
- compiler/astutil/astutil_test.go
- compiler/internal/symbol/symbol_test.go
- compiler/internal/typeparams/collect_test.go
- compiler/internal/typeparams/instance_test.go
- compiler/typesutil/typenames_test.go
- internal/srctesting/srctesting.go
- internal/srctesting/srctesting_test.go
This will be useful for testing cross-package generic instance discovery.
Updated #1013
> Refactor srctesting to support parsing and checking multiple packages.

- compiler/internal/typeparams/collect.go
- compiler/internal/typeparams/collect_test.go
- compiler/internal/typeparams/instance.go
- compiler/internal/typeparams/instance_test.go
- compiler/package.go
- Add PackageInstanceSets type to organize instances by package the instantiated object belongs to.
- Update Collector and related code to work with PackageInstanceSets.
Changes necessary to use this on the compiler side are not implemented yet, so we still can't _compile_ the code with generic instances across packages.
Updates #1013
> Support collecting instances across packages in typeparams.Collector.

- build/build.go
- build/context_test.go
- tool.go
The build.Context.Import method no longer populates build.Package.PkgObj for imports under the Goroot directory. This meant that the unit-tests used the context needed to be updated to no longer check PkgObj and that we needed a way to indicate to users when no install location is defined.
GopherJS only uses PkgObj when finding a location during a `gopherjs install` of a command package (i.e. `package main`) and no other install locations can be found for the current user. It seemed to me that it would be rare for the user to not have access to any other install location, attempt to fall back to PkgObj whilst installing something from Goroot, not impossible, but unlikely.
This is part of [#1270](https://github.com/gopherjs/gopherjs/issues/1270). The CI will continue to fail since we don't …
> [go1.20] Context import update for 1.20

- compiler/natives/src/sync/map.go
This is a temporary change to quiet complaints from natives using `sync` since `sync.Map` uses the `atomic.Pointer[T]` that was removed for generic-less go1.19.
CI will still be failing because of `sync/atomic/type.go:40:10: undefined: Pointer` where `var _ = &Pointer[int]{}` got added. If that wasn't there then after this change the tests should no longer be failing for an undefined `atomic.Pointer` from `sync.Map` when importing `sync`.
> [go1.20] Added temporary generics override for sync.Map

- circle.yml
- compiler/internal/typeparams/utils.go
- compiler/internal/typeparams/utils_test.go
- compiler/package.go
- internal/experiments/experiments.go
- internal/experiments/experiments_test.go
- internal/srctesting/srctesting.go
This commit adds support for GOPHERJS_EXPERIMENT environment variable that can be used to enable experimental functionality in the compiler.
Experiment flags can be easily added or removed by updating fields of the internal/experiments.Flags struct. For now, only boolean flags are supported, but it should be easy enough to extend if needed.
Users need to have GOPHERJS_EXPERIMENT=generics set in their environment to enable support. Adding the flag will allow us to merge generics support into the main branch before it's fully production-ready without creating unnecessary confusion for the users.
Updates #1013
> Guard generics support behind an experiment flag.

- compiler/natives/src/time/format.go
- compiler/natives/src/time/format_rfc3339.go
All these overrides are temporary while generics development is in progress.
A few methods in `time` use generics to allow `string` or `[]byte` to be used for formatting and parsing. To make these work I copied the method that needed to be temporarily replaced, then changed the generic parameter to `any`. The only complication is that one of these methods returns a generic type, meaning anything calling it has to have the value cast and thus overwritten too.
This is part of [#1270](https://github.com/gopherjs/gopherjs/issues/1270). After these changes (and removing `var _ = &Pointer[int]{}` from `sync/atomic/type.go:40`) running `go1.20.14 install -v && gopherjs build -v net/http` results in:
```
go1.20.14/src/os/file_unix.go:119:1: gopherjs: //go:linkname can not insert local …
```
> [go1.20] Added temporary generics override for time formatting

- compiler/natives/src/os/os.go
Between go1.19 ([here](https://cs.opensource.google/go/go/+/refs/tags/go1.19.13:src/os/proc.go;l=78)) and go1.20 ([here](https://cs.opensource.google/go/go/+/refs/tags/go1.20.14:src/os/proc.go;l=80)), the `os` link to the runtime beforeExit got a parameter containing the exitCode. Since a JS app doesn't shutdown like an executable, this method was no-op'ed in the native overrides.
This PR is just to add that missing parameter. This is part of [#1270](https://github.com/gopherjs/gopherjs/issues/1270).
> [go1.20] Update runtime_beforeExit to have exit code parameter.

- compiler/linkname.go
- compiler/linkname_test.go
- compiler/natives/src/net/fd_unix.go
The linkname directive, `//go:linkname localname [importpath.name]`, now optionally allows one-argument forms. [Details found in compiler directives document](https://pkg.go.dev/cmd/compile#hdr-Compiler_Directives). There was also a `TODO` in `linkname.go` to check for any additional arguments. The `os` package had a new insert-link to `net` that needed to be ignored and handled in the native overrides.
- I reorganized the `parseGoLinknames` method to separate it into:
- reading the linkname from the comment
- checking if the linkname is supported by GopherJS
- I added two methods to check for known links to ignore:
- one method is for specific var-links
- one method is for specific insert-links or any insert-links in specific packages
- I added the native override for `net.newUnixFile` …
> [go1.20] Updated the linkname to handle new directives

- compiler/natives/src/testing/example.go
Fixing an indirection error on `*chatty`. The [`chatty` value](https://cs.opensource.google/go/go/+/refs/tags/go1.20.14:src/testing/testing.go;l=454) is now [`struct{ on, json bool }`](https://cs.opensource.google/go/go/+/refs/tags/go1.20.14:src/testing/testing.go;l=486-489). The native override of `runExample` needed to be updated to match the changes to [go repo version (moved to `run_example.go`)](https://cs.opensource.google/go/go/+/refs/tags/go1.20.14:src/testing/run_example.go;l=22) while retaining the original override reason, [use temporary file rather than os.Pipe for testing examples](https://github.com/gopherjs/gopherjs/commit/7d94d732be268c4904141f8b8604eb2d6d6544a1). This is part of https://github.com/gopherjs/gopherjs/issues/1270
> [go1.20] Update test run example native override

- compiler/linkname_test.go
- tests/gorepo/run.go
This adds some more known fails for go1.20
This also fixes some `SymName` --> `symbol.Name` that I missed when merging master into go1.20
This is part of https://github.com/gopherjs/gopherjs/issues/1270
> [go1.20] More known fails and a fix

- build/build.go
During one of the updates to the parse and augmentation code, I accidentally left this extra `pruneImport` call. It isn't needed because inside of `augmentOverlayFile` [`pruneImport` (seen here)](https://github.com/gopherjs/gopherjs/blob/master/build/build.go#L322) will be called when the overlay file changes. So this left over one doesn't affect the result, it just wastes time.
> Remove extra pruneImport

- compiler/prelude/jsmapping.js
- tests/js_test.go
This is a fix for https://github.com/gopherjs/gopherjs/issues/1300
Now that externalization work better for `nil` or `zero` to `null` (done in https://github.com/gopherjs/gopherjs/pull/1194 as part of https://github.com/gopherjs/gopherjs/issues/617), we need to be able to internalize `null` values into `nil` or `zero`. Currently we get an exception because internalization isn't expecting a `null` value for a slice or array.
Internalization of an externalized array creates a copy making the value unassignable (see https://github.com/gopherjs/gopherjs/issues/1302). Until that is fixed, trying to internalize a null array will simply throw an exception. This is favorable over returning a zero value which will quietly hide the array problem and still not be assignable.
> Fixing internalization of null slice and array fields

- tests/gorepo/run.go
The Go file [`go1.20.14:test/run.go`](https://cs.opensource.google/go/go/+/refs/tags/go1.20.14:test/run.go) added more handling of the test flag arguments. Since some of the new tests for go1.20 use these flags, I updated the flag parsing into the GopherJS copy of the same runner, `gorepo/run.go`. These updates are nearly identical copies of the code from the Go repo. Any deviations I've commented with a `// GOPHERJS:` comment. This is part of https://github.com/gopherjs/gopherjs/issues/1270
Other than being able to handle more flags, the only main change was adding the timeout flag ability. The comment in the timeout (i.e. "This command-timeout code adapted...") is from the original source code.
Here is an example of a test, [fixedbugs/issue59334.go](https://cs.opensource.google/go/go/+/r …
> [go1.20] Updated gorepo test flag handling

- compiler/expressions.go
- tests/numeric_test.go
Before this change, GopherJS compiler emitted `(f >> 0)` expression to convert a float64 `f` to any non-64-bit unsigned integer type. This is incorrect, because `>>` is a signed bitshift operator in JS, so the returned value remained signed. Moreover, it did not take into account to bit size of the target type.
By removing the switch cause, we make the compiler fall through to the default clause where `fc.fixNumber()` actually does the right thing, taking the target into account.
Fixes #733.
Amazingly, this is what was causing flakiness of the `hash/maphash.TestHashHighBytes` since Go 1.19. There, the 64-bit hash value was computed as `(uint64(hi) << 32) | uint64(lo)`, where `hi` and `lo` were randomly-generated `unit32` values. In turn, those values were generated by converting a random …
> Fix float64 to uint{8,16,32} conversion.

- compiler/expressions.go
- compiler/prelude/prelude.js
- tests/js_test.go
go1.20 added [`unsafe.SlideData`](https://pkg.go.dev/unsafe@go1.22.2#SliceData), [`unsafe.String`](https://pkg.go.dev/unsafe@go1.22.2#String), and [`unsafe.StringData`](https://pkg.go.dev/unsafe@go1.22.2#StringData).
For the following reasons, this PR only adds `unsafe.SliceData`. The tests for this change are in the Go repo tests of this builtin function. This is part of https://github.com/gopherjs/gopherjs/issues/1270
`unsafe.SliceData` is something that GopherJS can handle because of how, even when empty, GopherJS slices have an array that can be pointed to.
The only thing we can't handle is how using the "unspecified memory address" works right now, [seen in this playground](https://goplay.tools/snippet/vr02QEJUWAG), but there are no promises for how that should work and no one should …
> [go1.20] Added support for unsafe.SliceData

- compiler/expressions.go
- tests/numeric_test.go
When working in go1.20 I ran into crypto mathematics that failed because `uint` is using `*`. The math overflowed the JS int causing it to switch to using an exponent and dropping the LSBs. Crypto needs those LSBs and expected the value to rollover. Using `$imul` instead of `*` fixes this problem. Since `uint` is equivalent to `uint32` in GopherJS and `int32`, `uintptr`, `uint32`, and `int` were already using `$imul` I figured that `uint` should probably be using it too.
> [GopherJS emulates a 32-bit environment. This means that `int`, `uint` and `uintptr` have a precision of 32 bits.](https://github.com/gopherjs/gopherjs/blob/master/README.md?plain=1#L159)
Even though this issue was discovered while working on go1.20, the fix isn't specifically related to go1.20. This should help anyone …
> Changed `uint` to use `$imul`

- compiler/natives/src/encoding/gob/gob.go
- compiler/natives/src/go/token/position.go
- compiler/natives/src/internal/godebug/godebug.go
- compiler/natives/src/net/http/http.go
- compiler/natives/src/sync/atomic/atomic.go
- compiler/natives/src/time/export_test.go
Temporarily overriding some more generics for go1.20 without generics while generics are still being worked on.
This also includes a work around to make CI pass the generic type check for the `atomic.Pointer[T]`. Since generics are being parsed correctly, I simply stripped all the functions off of `atomic.Pointer[T]` so that it can't be used but left an empty structure in it's place so that the type check at [go1.20.14:src/sync/atomic/type.go:40](https://cs.opensource.google/go/go/+/refs/tags/go1.20.14:src/sync/atomic/type.go;l=40) passes. This will help the CI for go1.20 produce much more useful errors since instead of always failing in `atomic`.
> [go1.20] Temporarily overriding generics for go1.20

- compiler/natives/src/internal/coverage/slicereader/slicereader.go
- compiler/natives/src/math/rand/rand.go
- compiler/natives/src/net/http/client_test.go
- compiler/natives/src/net/http/clientserver_test.go
- compiler/natives/src/strings/strings_test.go
- compiler/natives/src/syscall/syscall_js_wasm.go
This is a collection of native overrides needed for go1.20.
These changes are not related to the generics work.
The CI will continue to fail for go1.20 after this change but this will remove several errors from the failures. You may only see the type check error in atomics from [go1.20.14:src/sync/atomic/type.go:40](https://cs.opensource.google/go/go/+/refs/tags/go1.20.14:src/sync/atomic/type.go;l=40) depending on if the other override tickets have gotten in yet or not.
> [go1.20] Native overrides for go1.20 (not generics related)

- compiler/natives/src/crypto/ecdh/nist.go
- compiler/natives/src/crypto/ecdsa/ecdsa.go
- compiler/natives/src/crypto/ecdsa/ecdsa_test.go
- compiler/natives/src/crypto/internal/boring/bcache/cache.go
- compiler/natives/src/crypto/internal/boring/bcache/cache_test.go
- compiler/natives/src/crypto/internal/nistec/nistec_test.go
- compiler/natives/src/crypto/internal/nistec/wrapper.go
I was holding off on these changes until I could figure out what was wrong with a large part of crypto (turns out the issue was in `uint` and unrelated to the native overrides for crypto). Since that is now merged, here is the updates to the generics native overrides for crypto.
In go1.20 crypto the curves were broken up into nearly identical parts. Our original go1.19 overrides could be reused for most of these changes with minor rework, so that's what I did. I imported the shared override implementation each place the curve was needed.
This also includes an update to the cache removal. These are not generics related, we just can't handle the garbage collect hooks for the crypto cache, so we just make it always a cache miss.
CI will still fail for go1.20. We're missing an unrelated …
> [go1.20] Updating generics overrides for crypto

- compiler/natives/src/internal/godebug/godebug.go
- compiler/natives/src/runtime/runtime.go
- compiler/natives/src/syscall/syscall_js_wasm.go
- tests/runtime_test.go
In `internal/godebug` the `setUpdate` method is used to watch for changes to the environment variable `GODEBUG`. This is used by tests such as the `archive/zip` test `TestInsecurePaths` or any test using [`t.Setenv`](https://pkg.go.dev/testing@go1.22.3#T.Setenv).
To solve this I added a way to inject a JS `Proxy` into `process.env` that calls a callback when any environment variable is set, the callback will handle the rest of the update and call the function provided to `setUpdate`.
Testing this was a little hard since `godebug` is used by tests. I solved this by creating a go:link from a test that is external to `godebug`.
> [go1.20] internal/godebug env watcher update

- compiler/natives/src/reflect/reflect.go
- compiler/prelude/prelude.js
- compiler/prelude/types.js
- tests/arrays_test.go
Fixing the `reflect` method `Value.Grow` that grows a slice to a contain a minimum specified capacity. This required the [`grow`](https://cs.opensource.google/go/go/+/refs/tags/go1.20.14:src/reflect/value.go;l=2795-2807) method to be updated so that it can call into JS. I split the `append` method to create a `growSlice` method which functions similar to [`reflect.growslice`](https://cs.opensource.google/go/go/+/refs/tags/go1.20.14:src/reflect/value.go;l=3846).
CI will still fail right now because `internal/godebug.setUpdate` needs to be implemented. It is implemented in another PR. With both this and the `setUpdate` change the `TestGrow` tests pass.
This does not fix the issue with `Value.extendSlice` used by `Value.Append`. I'm fixing that in another PR.
> [go1.20] Fixing reflect Value.Grow

- compiler/natives/src/sync/sync.go
Add in the `runtime_SemacquireRWMutexR` and `runtime_SemacquireRWMutex` methods. I routed them both through the existing `runtime_SemacquireMutex` since "they're functionally identical." according to below.
From the [source](https://cs.opensource.google/go/go/+/refs/tags/go1.20.14:src/sync/runtime.go;l=16-26)...
```Go
// Semacquire(RW)Mutex(R) is like Semacquire, but for profiling contended
// Mutexes and RWMutexes.
// If lifo is true, queue waiter at the head of wait queue.
// skipframes is the number of frames to omit during tracing, counting from
// runtime_SemacquireMutex's caller.
// The different forms of this function just tell the runtime how to present
// the reason for waiting in a backtrace, and is used to compute some metrics.
// Otherwise they're functionally identical.
func …
```
> [go1.20] Add SemacquireRWMutex

- compiler/natives/src/encoding/gob/gob.go
- compiler/natives/src/encoding/gob/gob_test.go
When I started working on go1.20 I added an override to encoding/gob `growSlice` to replace it's usage of generics. Once I got the transpile to work other issues popped up that hid a mistake. Those other issues are now taking care of so this issue came back up. I fixed the mistake and skipped some tests checking mallocs. Additionally, I checked `TestEndToEnd` override since it has an old TODO on it. It appears the issue with the Marr field still exist so I left it alone.
The experimental generics can handle encoding/god without the override to `growSlice` now. The unit-tests pass in the same amount of time (within some variance). However, until generics is ready to get out of experimental mode, the overrides for generics are left in. Even after release of generics, this doesn't affect any …
> [go1.20] Fixing a encoding/gob override

- compiler/natives/src/internal/unsafeheader/unsafeheader.go
- compiler/natives/src/internal/unsafeheader/unsafeheader_test.go
- compiler/natives/src/reflect/reflect.go
- compiler/prelude/prelude.js
Overrode the remaining uses of `unsafeheader.Slice` since GopherJS implemented slices differently. The remaining use was in `cvtSliceArray` used by methods like [Value.Convert](https://pkg.go.dev/reflect@go1.20.14#Value.Convert).
The CI will still not pass yet, but this will fix the tests like `TestConvert` so they pass. With the prior tickets for reflect merged, this should also get the `reflect` package to pass.
This is a follow up to #1321. This is part of #1270
> [go1.20] Removing remaining uses of `unsafeheader.Slice` from reflect

- compiler/natives/src/strings/strings.go
Overriding [`strings.Repeat`](https://pkg.go.dev/strings@go1.20.14#Repeat) with [go1.19's implementation](https://cs.opensource.google/go/go/+/refs/tags/go1.19.13:src/strings/strings.go;l=524-556) because it is significantly faster than the [go1.20 implementation](https://cs.opensource.google/go/go/+/refs/tags/go1.20.14:src/strings/strings.go;l=521-582) and [JS's String.replace](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat) gives different results.
The CI will still fail for go1.20 but now it will fail faster. This is part of #1270 
In the go1.20 implementation of `strings.Repeat` the function was changed to use chunks with a limited size because:
> Past a certain chunk size it is counterproductive to use larger chunks as the source of the …
> [go1.20] Repeat go1.19 strings.Repeat for go1.20

- .github/workflows/ci.yaml
- compiler/natives/src/compress/gzip/example_test.go
- node-syscall/package-lock.json
- node-syscall/syscall.cc
- package-lock.json
NodeJS 12 has been end-of-life since 2022-04-30, so there's not much value in testing against it. 18 is the current oldest supported LTS version, so we use that in CI. I also had to make a few minor updates to the `node_syscall` extension to make sure it continues working.
> Update NodeJS from 12 to 18

- .github/workflows/measure-size.yml
When I was bumping the Go version in CI to 1.20.14, I forgot to also include `GOPHERJS_EXPERIMENT: generics` in `measure-size.yml`. Without generics enabled for go1.20, the [type check in atomic](https://cs.opensource.google/go/go/+/refs/tags/go1.20.14:src/sync/atomic/type.go;l=40) causes GopherJS to fail the build that is being measured.
This change should get `measure-size.yml` CI to pass for go1.20 branch. (The go1.20 branch doesn't have the CI improvements from master yet so they will take some time to run.)
> [go1.20] Adding experimental generics flag to measure-size.yml for go1.20

- compiler/prelude/types.js
- tests/arrays_test.go
The GopherJS transpiler will converts
```Go
slice := []byte{1, 2, 3, 4}
array := [4]byte(slice)
```
into
```JS
array = $clone(($clone(slice, arrayType)), arrayType);
```
the `$clone` calls the copy method on the array type. The copy method used `src.length` that is undefined for a slice. I added to the array type copy method to also allow for conversion from slices into arrays. The secondary `$clone` is from the assignment of an array to an array.
This will fix the issues in `net/netip` where they are converting slices of different lengths into arrays for ip addresses. This change should fix the last issue in GopherJS Tests so it should pass. Most of CI should pass, but `measurement_size.yml` will still fail in this PR (it's fixed by another PR).
> [go1.20] Added copy from slice to array copy

- README.md
- package-lock.json
- package.json
- tool.go
- We aren't using uglify-es since we switched to esbuild for prelude minification.
- We no longer need source-map-support module since Node supports the equivalent functionality natively.
Our only NPM dependency at this point is the node-syscall module, which is deprecated and will be removed at some future point (https://github.com/gopherjs/gopherjs/issues/1328).
> Remove npm dependencies we don't need anymore

- compiler/decls.go
- compiler/expressions.go
- compiler/functions.go
- compiler/natives/src/reflect/reflect.go
- compiler/natives/src/reflect/reflect_test.go
- compiler/package.go
- compiler/utils.go
- Factor out unimplemented function body generation into a helper.
- Remove an unnecessary special case for methods with array-pointer receivers.
- Move method translation logic into its own method, similar to the existing one for standalone functions.
- Assign identities to all function literals and use them as funcRefs. This unifies translation logic between named and literal functions and reduces the number of arguments we have to pass around.
- Add some comments to the existing code.
Updates #1013
> Final round of refactoring ported from the original generics branch.

- compiler/compiler.go
- compiler/decls.go
- compiler/expressions.go
- compiler/internal/dce/collector.go
- compiler/internal/dce/dce_test.go
- compiler/internal/dce/filters.go
- compiler/internal/dce/info.go
- compiler/internal/dce/selector.go
- compiler/package.go
- compiler/statements.go
- compiler/utils.go
The dead-code elimination (DCE) code has two filter strings and dependencies as a set of strings. The strings have special meanings such as both empty strings indicate always alive. To help facilitate future changes to DCE, I'm moving the DCE code to it's own package. Also I'm making some methods to set a decl's DCE filters and deps to ensure that the names are continued to be set the same as new changes are made.
These changes should have only minor functional changes, everything should continue to function as before. These changes are mostly a minor refactor to encapsulate DCE design decisions. The CI should continue to pass.
This is related to #1013 and #1270 work since the future changes to DCE is to include removal of dead generic code instantiations, e.g. allow `List[int]` to be …
> Moving DCE into its own package

- compiler/internal/typeparams/map.go
- compiler/internal/typeparams/map_test.go
To finish updating blocking for instances of generic functions, I needed an instance map that also has a way to iterate key/value pairs (or a way to get list of keys) and to delete keys. I updated the existing `InstanceMap` by pulling some more ideas from the [typeutil.Map](https://pkg.go.dev/golang.org/x/tools/go/types/typeutil#Map).
This is related to #1013 and #1270
> Adding more functions to InstanceMap

- compiler/compiler_test.go
- go.mod
- go.sum
- internal/srctesting/srctesting.go
This adds tests for the dead-code elimination (DCE) package into the compiler. The compiler performs many tasks that are related to DCE such as setting Decl's names and dependencies. These tests are designed like an integration test to ensure that the correct information is being given to the DCE and that the DCE is doing the correct things with that information.
This will introduce some TODO's that are resolved by the next part #1340. These TODO's exemplify the changes needed to be made to the DCE to properly handle generics and type instances. Double check that I'm not taking crazy pills with these TODO's and that they make sense to be the thing that needs to be fixed in the next part.
This is related to #1013 and #1270
---
🍰 As an added bonus; I upgraded the existing test to stop using …
> Adding DCE integration tests in compiler

- compiler/compiler_test.go
- compiler/expressions.go
This is a fix for #841 
I added a check to see if the expression used as the argument inside the `len` contains binary expressions. If a binary expression exists, then the expression is parenthesized. For example, `len(a)` will still be translated to `a.length` without the parenthesis. `len(a +b)` was getting translated to `a + b.lengh` (which was the problem), but now get translated into `(a + b).length` with parenthesis. We don't want to add parenthesis all the time to avoid making the resulting JS larger when not needed.
This will cover any combination of concatenations of variable and literal strings, e.g. `len(a + b)`, `len(a + ":" + b)`. The issue exists only when a basic type is used in `len`, i.e. `string`. I didn't limit the check to only being additions (`+`) for concatenation …
> Fixing issue in `len` with string concatenation in argument

- compiler/functions.go
- compiler/internal/analysis/defer.go
- compiler/internal/analysis/info.go
- compiler/internal/analysis/info_test.go
- compiler/internal/typeparams/map.go
- compiler/internal/typeparams/map_test.go
- compiler/typesutil/typelist.go
While I was doing other work I ran into a few issues and fixed them:
1. **Unused Generic Functions**: Unused generic functions and methods that perform calls were making requests with the type parameters, e.g. `func Foo[T any]() { Bar[T]() }` will make a request for the function information for `Bar[T]` with `T` being the type parameter. This was because if there were no instances, I assumed that meant that it was a non-generic function, but I totally missed the possibility that it is a generic function that just isn't used. I now check for instances and check if the function is generic and if it is unused and generic, skip over the function and don't bother making a FuncInfo for it. Since it is unused, it can't be needed by anything else other than other unused functions.
2. **Function …
> Fixing issues in analysis around generics

- compiler/natives/src/crypto/tls/handshake_test.go
Master started failing CI because `TestVerifyConnection` and  `TestResumptionKeepsOCSPAndSCT` failed with "bad certificate". Digging into the problem revealed that [`testRSACertificateIssuer`](https://cs.opensource.google/go/go/+/refs/tags/go1.19.13:src/crypto/tls/handshake_test.go;l=434), a hardcoded byte array of a certificate, expired in 2025-01-01. The last update to those that certificate for go1.19.13 is in [2019-06-20](https://cs.opensource.google/go/go/+/0884bca05a278e7f8783be3545a88a26b14dd4e4), so they gave it 6 years before expiring.
Added overrides to skip those tests with a comment to check in future versions.
It appears that the same string in [go1.23.1](https://cs.opensource.google/go/go/+/refs/tags/go1.23.1:src/crypto/tls/handshake_test.go;l=524) but have added code to …
> Skipping crypto tests with expired certificate

- build/build.go
- internal/testmain/testmain.go
- internal/testmain/testmain_test.go
- tool.go
This is the start of several changes to get generic information propagated across package lines.
This changes how packages are loaded so that they are not converted into `Archive`s right away. This does mean that `Archive` caching has been disabled. With the `Archive`s creation delayed, we have two phases:
1. **Parse**: The parse phase uses `BuildPackage`s to determine the files that are needed to be parsed for a package and determine the imports that are required for a package. The result of the parse phase will be `ParsedPackage`s. All the `ParsedPackage`s needed for a project will be gotten prior to moving onto the compile phase.
2. **Compile**: The compile phase will take the root `ParsedPackage` and start compiling it, compiling any imported `ParsedPackage` as it goes. Each compile …
> Separate Parsing and Compiling

- build/build.go
- compiler/compiler_test.go
- compiler/decls.go
- compiler/internal/analysis/info.go
- compiler/internal/analysis/info_test.go
- compiler/package.go
- compiler/sources/sources.go
- internal/srctesting/srctesting.go
> 3. build system needs to be changed to collect generic instance information and propagate it across package boundaries. This would require reorganizing build package into loading all packages first, analyzing them, and then passing to the compiler, which is different from today's behavior where imported packages are loaded and compiled on-demand when compiler needs them. The tricky part here would be making sure build cache accounts for the fact that dependent packages may influence the set of generic instances of the dependency packages. - [from this slack comment by nevkontakte](https://gophers.slack.com/archives/C039C0R2T/p1721859938577319)
- This leverages the prior work to making Sources a more important part of the Build process.
- This add the type information and linkname …
> Perform cross package type analysis

- compiler/compiler_test.go
- compiler/decls.go
- compiler/expressions.go
- compiler/functions.go
- compiler/internal/analysis/info.go
- compiler/internal/analysis/info_test.go
- compiler/internal/symbol/symbol.go
- compiler/internal/typeparams/collect.go
- compiler/internal/typeparams/collect_test.go
- compiler/internal/typeparams/instance.go
- compiler/internal/typeparams/map.go
- compiler/internal/typeparams/map_test.go
- compiler/internal/typeparams/utils.go
- compiler/package.go
- compiler/utils.go
- internal/govendor/subst/export.go
- internal/govendor/subst/subst.go
- internal/govendor/subst/subst_test.go
- internal/govendor/subst/util.go
- internal/srctesting/srctesting.go
Adding type parameters from a function into the nested types inside of that function. For example:
```Go
func Foo[T any]() {
type Bar struct { x T }
type Baz[U any] struct { x T; y U }
...
}
```
The type `Bar` is concrete (i.e. not generic) however it acts like it is generic because it is nested in a generic function. If the function is called like `Foo[string]()` then `Bar` innately is different from if the function is called like `Foo[int]()`. The nesting type parameters is shown like `Bar[T;]` and instantiated like `Bar[string;]` and `Bar[int;]`.
In Go the `;` in the type parameters isn't present if the nested type is concrete. `Baz` is generic meaning the `;` indicates the separation between the nested type parameters and the objects own type parameters. For example if `Baz[string]{}` …
> Adding nested type support

- compiler/compiler_test.go
- compiler/declNames.go
- compiler/decls.go
- compiler/expressions.go
- compiler/internal/dce/README.md
- compiler/internal/dce/collector.go
- compiler/internal/dce/dce_test.go
- compiler/internal/dce/filters.go
- compiler/internal/dce/info.go
- compiler/internal/typeparams/utils.go
- compiler/internal/typeparams/utils_test.go
- compiler/statements.go
- compiler/utils.go
This is a follow up to #1374, so wait until that is merged to master prior to reviewing this PR.
Or only look at the [DCE commit's changes](https://github.com/gopherjs/gopherjs/pull/1375/commits/5bcfc68d50b29dfe4c7f6ba96bfd20769b15734a).
Updated DCE to support nested types. See "Fixing DCE" in summary of #1370.
The update will make it so that types nested inside of a function or method are only marked as alive when the function or method is marked as alive.
I also fixed the issue in `FindNestingFunc` around nested types inside of methods. See the note at the end of the summary for #1370
This is related to #1013 and #1270
> DCE update to support nested types

- compiler/astutil/astutil.go
- compiler/compiler_test.go
- compiler/decls.go
- compiler/expressions.go
- compiler/functions.go
- compiler/internal/analysis/info.go
- tests/misc_test.go
- tests/otherpkg/otherpkg.go
In several cases we expected the target expression (e.g. `e.X`) of an indexer expression (i.e.`IndexExp` and `IndexListExp`) to be an `*ast.Ident`, which is not true for all cases. I wrote a test containing a bunch of the cases I could think of that would put a `*ast. SelectorExpr` as the target expression of the indexer expression. Most of the unhandled cases were around calling an exported generic function from a different package, e.g. `package.Foo[int]()`. This must have slipped through the cracks when we were doing other generic stuff since it isn't too common in tests (ours and Go's) to have multiple packages.
I also fixed how exported functions are written to the package object. It was overwriting the package variable with the individual instances instead of setting the list of …
> Adding selectors to index handling for generics
