gopherjs/gopherjs

build/build.go
=> build: update the osext import path (moved to github).

compiler/natives/net/http/http.go
The `(*http.Response).ContentLength` field was incorrectly being set to `0` during `HEAD` requests. This patch uses the `Content-Length` response header if it exists, otherwise leaves it at `-1`, documented in `net/http` to mean "don't know"; this matches the behavior of Go's `net/http` package.
=> natives/net/http: set response ContentLength from headers on HEAD requests

tool.go
This is nice when using with gopherjs serve, because it already recompiles on browser refresh. This allows one to switch between code editor and browser for a faster iteration cycle. No need to also switch to the terminal to see errors, as now both compilation and runtime errors are visible in browser console.
I'm backporting some enhancements from my `gopherjs_serve_html` tool, so I can stop using it and rely on `gopherjs serve` full time.
This resolves a future enhancement that was mentioned in https://github.com/gopherjs/gopherjs/issues/121#issuecomment-87495493.
=> gopherjs serve: Display compilation errors in browser console.

README.md
=> README: Add GopherJS Slack channel to community section.

tool.go
This is more consistent with all other go and gopherjs tools, commands.
Closes #248.
=> gopherjs serve: Use {base}.js rather than main.js.

compiler/prelude/jsmapping.go
Attempt to follow suggestion in https://github.com/gopherjs/gopherjs/issues/287#issuecomment-136315076.
Not quite sure it's an improvement at this time, but maybe it just needs more work?
No handling of `null` or `undefined` values instead of `Date`. Also no support for `*time.Time` at this time.
Feel free to make changes as you see fit here. This is a PR into PR #288 (branch `fix-287`).
=> WIP: Refactor attempt to move t === timePkg.Time check out.

compiler/prelude/jsmapping.go, js/js_test.go
~~Don't merge, this PR is a WIP (more commits to be pushed) and in need of review.~~ Ready for review.
Add a failing test case, then fix #287.
=> Fix internalize case for Date into time.Time struct.

compiler/analysis/info.go, compiler/analysis/sideeffect.go, compiler/expressions.go, compiler/filter/assign.go, compiler/filter/incdecstmt.go, compiler/package.go, compiler/statements.go, compiler/utils.go, tests/run.go
=> Fix #300 and improve code on the way

compiler/prelude/types.go
Fixes Circle CI build.
Before: https://circleci.com/gh/gopherjs/gopherjs/593.
After: https://circleci.com/gh/gopherjs/gopherjs/594.
=> Add missing semicolon in JS that causes issues with minification.

tool.go
This is a followup to @neelance's [comment](https://github.com/gopherjs/gopherjs/pull/376#issuecomment-171467723) on issue #376.  It adds support for the -o/--output option (borrowed from 'build' mode) to `test` mode.
The current implementation *only* outputs the file, rather than also running the tests. This may or may not be best. If the consensus is to run the tests, too, that change will be simple to make.
=> Add the ability to save output of test compile

README.md, tool.go
=> Add optional root argument to gopherjs serve. Fixes #384

circle.yml
=> circle: Update to Go 1.6.2.

README.md
=> Update the url of the game benchmark.

compiler/vendor/github.com/neelance/astrewrite/LICENSE, compiler/vendor/github.com/neelance/astrewrite/simplify.go, compiler/vendor/vendor.json
```
govendor fetch github.com/neelance/astrewrite
```
Apply latest changes in `astrewrite`:
https://github.com/neelance/astrewrite/compare/d91ea99fd1b9461e120645b0b5a1ada8462aae9e...99348263ae862cc230986ce88deaddbf7edcc034
=> compiler: Update astrewrite.

circle.yml
=> circle: Update to Node 6.2.2.

compiler/version_check.go, tool.go
Helps #500.
```
$ gopherjs version
GopherJS 1.7-1
```
=> Add GopherJS compiler version and command to print it.

build/build.go, tool.go
=> Add plumbing to support build tags in test mode.

README.md
=> README: Document that cgo is not supported.

README.md
The linked document covers things like code style, code generation, and other notes and expectations for this project.
Resolves #517.
=> README: Add "GopherJS Development" section.

doc/syscalls.md
=> Document that system calls block other goroutines.

tool.go
Fixes #556 .
I threw this together before work this morning. If I overlooked something, please let me know.
=> Add minimal wrapper around 'go doc'

tool.go
=> Add --benchtime support

compiler/utils.go
If names are equal, sort ties by position.
Fixes #679
=> Ensure that sorting of variables is stable

compiler/prelude/goroutines.go
=> Remove unused argument 'direct'

circle.yml
=> ci: upgrade to use Go 1.10.1

circle.yml
Reference: https://groups.google.com/d/msg/golang-announce/XwnlNhVZE5o/P1n8QJprAwAJ.
=> CI: Update to Go 1.11.2.

circle.yml
=> CI: fix breakage and update minor Go version

README.md
Mainly I'd like to advertise the user survey more broadly to folks who are not following us in Twitter or Slack, but also list a few other ways to contribute to the project while I'm at it.
=> Add "Help us make GopherJS better" section into the README.

tool.go
- Include Go package name in the temp file name.
- Close file handle to the temp file early, since we are not actually
using it.
- Clean the temporary file up after test execution finished to reduce
the clutter in the current directory.
I was also going to move temporary files into the OS's temp directory,
but it turns out using current directory is deliberate:
https://github.com/gopherjs/gopherjs/issues/303.
=> Improve temporary file management in `gopherjs test`.

build/build.go, compiler/compiler_test.go, compiler/package.go, go.mod, go.sum
=> Orders source files before compilation to ensure reproducible output

tool.go
This will be a helpful tool for performance issue investigations.
In order to implement this I also had to refactor use of `os.Exit()` in the main package, since it was preventing Cobra's post-run functions from executing.
=> Add flags to collect CPU and allocation profiles for GopherJS

tool.go
Setting stack size exactly to the system limit will cause node to
segfault before it has a chance to notice that it ran out of space. In
my experiemnts values closer than 64 KiB may still cause a segfault from
time to time.
I also changed the multiplier to 1024, since that's what v8 actually
uses for the flag value.
Fixes #470.
=> Improve nodejs stack size limit heuristic.

.std_test_pkg_exclusions, build/build.go, build/embed.go, compiler/natives/src/embed/embed.go, go.mod, go.sum, tests/testdata/legacy_syscall/main.go, tool.go
support go:embed
- gopherjs build/test/serve pkg
- gopherjs run/build simple.go
dep pkg [github.com/visualfc/goembed](https://github.com/visualfc/goembed)
Fixes https://github.com/gopherjs/gopherjs/issues/997
=> build: support go:embed

tool.go
allow setting the option to false with -s shorthand
Fixed https://github.com/gopherjs/gopherjs/issues/953
=> Make creation of source maps optional with a flag

compiler/decls.go, compiler/functions.go
I spotted a couple of minor improvements, and sending them in before diving back into the weeds...
- Use the existing helper to determine receiver type.
- And remove the TODO which I actually resolved in the previous pull request.
Updates #1013
=> Two minor cleanups in the generics branch.

compiler/analysis/escape.go, compiler/utils.go
This is just a rebase of https://github.com/gopherjs/gopherjs/pull/760 on current master.
fixes https://github.com/gopherjs/gopherjs/issues/759
=> Improve ordering of EscapingObjects

build/build.go, build/build_test.go
This ticket breaks up the `parseAndAugment` method into smaller methods which are easier to understand. This also adds unit-tests specifically for the augmentation methods that were extracted from `parseAndAugment`. This should have no affect on the functionality of `parseAndAugment` and is purely just reorganization.
`parseAndAugment` now has the following helper methods:
- `parseOverlayFiles`
- `parserOriginalFiles`
- `augmentOverlayFile`
- `augmentOriginalImports`
- `augmentOriginalFile`
=> Breakup parseAndAugment method

tests/gorepo/run.go
Some of the newer tests (e.g. [bug514](https://cs.opensource.google/go/go/+/refs/tags/go1.20.14:test/fixedbugs/bug514.go)) don't define the legacy "plus [build constraints](https://pkg.go.dev/cmd/go#hdr-Build_constraints)" (i.e. `// +build`) they only use "go build constraints" (i.e. `//go:build`) so the `test/gorepo/run.go` file needs to be updated. `test/gorepo/run.go` is a very similar to [test/run.go](https://cs.opensource.google/go/go/+/refs/tags/go1.20.14:test/run.go), in fact, it is a copy with modifications specific to GopherJS [per the original commit](https://github.com/gopherjs/gopherjs/commit/587ec90ef2ed1378ebfe602a8cc10bc657871191).
Therefore all of the updates I made are from the existing `go:test/run.go` code with minor differences. The differences are around things like …
=> Updated test/gorepo/run.go's build constraint checker

build/build.go, compiler/expressions.go, compiler/prelude/jsmapping.js, tests/js_test.go, tests/numeric_test.go
Keeping go1.20 up-to-date with master
CI will still not pass because we haven't gotten go1.20 to pass yet.
=> [go1.20] Pull master into go1.20

compiler/natives/src/reflect/reflect.go
Overrode the following to not use `unsafeheader.Slice` since GopherJS implemented slices differently:
- [`Value. SetZero`](https://pkg.go.dev/reflect@go1.20.14#Value.SetZero)
- [`Value.UnsafePointer`](https://pkg.go.dev/reflect@go1.20.14#Value.UnsafePointer)
- `Value.extendSlice` used by [`reflect.Append`](https://pkg.go.dev/reflect@go1.20.14#Append) and [`reflect.AppendSlice`](https://pkg.go.dev/reflect@go1.20.14#AppendSlice)
The last use of `unsafeheader.Slice` is in `cvtSliceArray` used by methods like [Value.Convert](https://pkg.go.dev/reflect@go1.20.14#Value.Convert). I will put that update into another PR.
The CI will still not pass yet, but this will fix the tests like `TestIsZero` and `TestAppend` so they pass.
=> [go1.20] Removing some uses of `unsafeheader.Slice` from reflect
